In [1]:
import pandas as pd
import numpy as np

# Load the datasets
train_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/05_patient_profile/train.csv'
test_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/05_patient_profile/test.csv'

train_df = pd.read_csv(train_data_path)
test_df = pd.read_csv(test_data_path)

# Display the first few rows of the training and test datasets
print("Training Data:")
display(train_df.head())
print("Test Data:")
display(test_df.head())

# Check the structure of the datasets
print("Training Data Info:")
train_df.info()
print("Test Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Test Data:")
print(test_df.isnull().sum())

# Check the distribution of the target variable
print("Distribution of the target variable in Training Data:")
print(train_df['outcome variable'].value_counts(normalize=True))

# Check the distribution of categorical and numerical features
categorical_features = train_df.select_dtypes(include=['object']).columns.tolist()
numerical_features = train_df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("Categorical Features:")
print(categorical_features)
print("Numerical Features:")
print(numerical_features)

# Visualize the distribution of numerical features
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features, 1):
    plt.subplot(3, 3, i)
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Visualize the distribution of categorical features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(categorical_features, 1):
    plt.subplot(3, 3, i)
    sns.countplot(x=feature, data=train_df)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

Training Data:

                     Disease Fever  ... Cholesterol Level Outcome Variable
0                Ebola Virus   Yes  ...            Normal         Positive
1  Conjunctivitis (Pink Eye)    No  ...              High         Positive
2               Pancreatitis    No  ...              High         Positive
3               Pancreatitis   Yes  ...            Normal         Negative
4            Hyperthyroidism   Yes  ...            Normal         Negative

[5 rows x 10 columns]

Test Data:

                                        Disease  ... Outcome Variable
0                                Hypothyroidism  ...         Positive
1                                   Tonsillitis  ...         Positive
2  Chronic Obstructive Pulmonary Disease (COPD)  ...         Positive
3                                  Lyme Disease  ...         Positive
4                                      Diabetes  ...         Positive

[5 rows x 10 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Disease               279 non-null    object
 1   Fever                 279 non-null    object
 2   Cough                 279 non-null    object
 3   Fatigue               279 non-null    object
 4   Difficulty Breathing  279 non-null    object
 5   Age                   279 non-null    int64
 6   Gender                279 non-null    object
 7   Blood Pressure        279 non-null    object
 8   Cholesterol Level     279 non-null    object
 9   Outcome Variable      279 non-null    object
dtypes: int64(1), object(9)
memory usage: 21.9+ KB
Test Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Disease               70 non-null     object
 1   Fever                 70 non-null     object
 2   Cough                 70 non-null     object
 3   Fatigue               70 non-null     object
 4   Difficulty Breathing  70 non-null     object
 5   Age                   70 non-null     int64
 6   Gender                70 non-null     object
 7   Blood Pressure        70 non-null     object
 8   Cholesterol Level     70 non-null     object
 9   Outcome Variable      70 non-null     object
dtypes: int64(1), object(9)
memory usage: 5.6+ KB
Missing values in Training Data:
Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64
Missing values in Test Data:
Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64
Distribution of the target variable in Training Data:

KeyError: 'outcome variable'

In [2]:
import pandas as pd
import numpy as np

# Load the datasets
train_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/05_patient_profile/train.csv'
test_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/05_patient_profile/test.csv'

train_df = pd.read_csv(train_data_path)
test_df = pd.read_csv(test_data_path)

# Display the first few rows of the training and test datasets
print("Training Data:")
display(train_df.head())
print("Test Data:")
display(test_df.head())

# Check the structure of the datasets
print("Training Data Info:")
train_df.info()
print("Test Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Test Data:")
print(test_df.isnull().sum())

# Check the distribution of the target variable
print("Distribution of the target variable in Training Data:")
print(train_df['Outcome Variable'].value_counts(normalize=True))

# Check the distribution of categorical and numerical features
categorical_features = train_df.select_dtypes(include=['object']).columns.tolist()
numerical_features = train_df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("Categorical Features:")
print(categorical_features)
print("Numerical Features:")
print(numerical_features)

# Visualize the distribution of numerical features
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features, 1):
    plt.subplot(3, 3, i)
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Visualize the distribution of categorical features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(categorical_features, 1):
    plt.subplot(3, 3, i)
    sns.countplot(x=feature, data=train_df)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

Training Data:

                     Disease Fever  ... Cholesterol Level Outcome Variable
0                Ebola Virus   Yes  ...            Normal         Positive
1  Conjunctivitis (Pink Eye)    No  ...              High         Positive
2               Pancreatitis    No  ...              High         Positive
3               Pancreatitis   Yes  ...            Normal         Negative
4            Hyperthyroidism   Yes  ...            Normal         Negative

[5 rows x 10 columns]

Test Data:

                                        Disease  ... Outcome Variable
0                                Hypothyroidism  ...         Positive
1                                   Tonsillitis  ...         Positive
2  Chronic Obstructive Pulmonary Disease (COPD)  ...         Positive
3                                  Lyme Disease  ...         Positive
4                                      Diabetes  ...         Positive

[5 rows x 10 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Disease               279 non-null    object
 1   Fever                 279 non-null    object
 2   Cough                 279 non-null    object
 3   Fatigue               279 non-null    object
 4   Difficulty Breathing  279 non-null    object
 5   Age                   279 non-null    int64
 6   Gender                279 non-null    object
 7   Blood Pressure        279 non-null    object
 8   Cholesterol Level     279 non-null    object
 9   Outcome Variable      279 non-null    object
dtypes: int64(1), object(9)
memory usage: 21.9+ KB
Test Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Disease               70 non-null     object
 1   Fever                 70 non-null     object
 2   Cough                 70 non-null     object
 3   Fatigue               70 non-null     object
 4   Difficulty Breathing  70 non-null     object
 5   Age                   70 non-null     int64
 6   Gender                70 non-null     object
 7   Blood Pressure        70 non-null     object
 8   Cholesterol Level     70 non-null     object
 9   Outcome Variable      70 non-null     object
dtypes: int64(1), object(9)
memory usage: 5.6+ KB
Missing values in Training Data:
Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64
Missing values in Test Data:
Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64
Distribution of the target variable in Training Data:
Outcome Variable
Positive    0.523297
Negative    0.476703
Name: proportion, dtype: float64
Categorical Features:
['Disease', 'Fever', 'Cough', 'Fatigue', 'Difficulty Breathing', 'Gender', 'Blood Pressure', 'Cholesterol Level', 'Outcome Variable']
Numerical Features:
['Age']

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-30 18:42:48.087 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': ['Disease', 'Fever', 'Cough', 'Fatigue', 'Difficulty Breathing', 'Gender', 'Blood Pressure', 'Cholesterol Level', 'Outcome Variable'], 'Numeric': ['Age'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import OneHotEncode

# Copy the DataFrames to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# List of categorical features to be one-hot encoded (excluding 'Disease')
categorical_features_to_encode = [col for col in categorical_features if col != 'Disease']

# Initialize the OneHotEncode tool
one_hot_encoder = OneHotEncode(features=categorical_features_to_encode)

# Fit and transform the training data
train_df_encoded = one_hot_encoder.fit_transform(train_df_copy)

# Transform the test data using the fitted model
test_df_encoded = one_hot_encoder.transform(test_df_copy)

# Display the first few rows of the encoded training and test data
print("Encoded Training Data:")
display(train_df_encoded.head())
print("Encoded Test Data:")
display(test_df_encoded.head())

Encoded Training Data:

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

                     Disease  ...  Outcome Variable_Positive
0                Ebola Virus  ...                        1.0
1  Conjunctivitis (Pink Eye)  ...                        1.0
2               Pancreatitis  ...                        1.0
3               Pancreatitis  ...                        0.0
4            Hyperthyroidism  ...                        0.0

[5 rows x 20 columns]

Encoded Test Data:

                                        Disease  ...  Outcome Variable_Positive
0                                Hypothyroidism  ...                        1.0
1                                   Tonsillitis  ...                        1.0
2  Chronic Obstructive Pulmonary Disease (COPD)  ...                        1.0
3                                  Lyme Disease  ...                        1.0
4                                      Diabetes  ...                        1.0

[5 rows x 20 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the latest DataFrame from the finished tasks
column_info_train = get_column_info(train_df_encoded)
column_info_test = get_column_info(test_df_encoded)

print("Column Info for Encoded Training Data:")
print(column_info_train)
print("\nColumn Info for Encoded Test Data:")
print(column_info_test)

Column Info for Encoded Training Data:
{'Category': ['Disease'], 'Numeric': ['Age', 'Fever_No', 'Fever_Yes', 'Cough_No', 'Cough_Yes', 'Fatigue_No', 'Fatigue_Yes', 'Difficulty Breathing_No', 'Difficulty Breathing_Yes', 'Gender_Female', 'Gender_Male', 'Blood Pressure_High', 'Blood Pressure_Low', 'Blood Pressure_Normal', 'Cholesterol Level_High', 'Cholesterol Level_Low', 'Cholesterol Level_Normal', 'Outcome Variable_Negative', 'Outcome Variable_Positive'], 'Datetime': [], 'Others': []}

Column Info for Encoded Test Data:
{'Category': ['Disease'], 'Numeric': ['Age', 'Fever_No', 'Fever_Yes', 'Cough_No', 'Cough_Yes', 'Fatigue_No', 'Fatigue_Yes', 'Difficulty Breathing_No', 'Difficulty Breathing_Yes', 'Gender_Female', 'Gender_Male', 'Blood Pressure_High', 'Blood Pressure_Low', 'Blood Pressure_Normal', 'Cholesterol Level_High', 'Cholesterol Level_Low', 'Cholesterol Level_Normal', 'Outcome Variable_Negative', 'Outcome Variable_Positive'], 'Datetime': [], 'Others': []}

In [6]:
from metagpt.tools.libs.feature_engineering import GeneralSelection
from sklearn.feature_selection import SelectKBest, chi2

# Copy the encoded data
train_df_encoded_copy = train_df_encoded.copy()
test_df_encoded_copy = test_df_encoded.copy()

# Remove the label column from the feature selection process
X_train = train_df_encoded_copy.drop(columns=['Outcome Variable_Negative', 'Outcome Variable_Positive'])
X_test = test_df_encoded_copy.drop(columns=['Outcome Variable_Negative', 'Outcome Variable_Positive'])
y_train = train_df_encoded_copy['Outcome Variable_Positive']

# Apply GeneralSelection to remove features with only one unique value
general_selector = GeneralSelection(label_col='Outcome Variable_Positive')
X_train_general = general_selector.fit_transform(X_train)
X_test_general = general_selector.transform(X_test)

# Apply SelectKBest to select the top 5 features
k_best_selector = SelectKBest(score_func=chi2, k=5)
X_train_k_best = k_best_selector.fit_transform(X_train_general, y_train)
X_test_k_best = k_best_selector.transform(X_test_general)

# Get the names of the selected features
selected_features = X_train_general.columns[k_best_selector.get_support()]
print("Selected Features:", selected_features)

# Add the label column back to the selected features
X_train_k_best_df = pd.DataFrame(X_train_k_best, columns=selected_features, index=X_train_general.index)
X_test_k_best_df = pd.DataFrame(X_test_k_best, columns=selected_features, index=X_test_general.index)
X_train_k_best_df['Outcome Variable_Positive'] = y_train
X_test_k_best_df['Outcome Variable_Positive'] = test_df_encoded_copy['Outcome Variable_Positive']

# Display the selected features in the training and test sets
print("Training Data with Selected Features:")
display(X_train_k_best_df.head())
print("Test Data with Selected Features:")
display(X_test_k_best_df.head())

KeyError: "['Outcome Variable_Positive'] not in index"