In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/wild_blueberry_yield/train.csv'
train_df = pd.read_csv(train_path)

# Display the first few rows of the dataset
print("First 5 rows of the dataset:")
display(train_df.head())

# Display the summary of the dataset
print("\nSummary of the dataset:")
display(train_df.describe())

# Check for missing values
print("\nMissing values in the dataset:")
display(train_df.isnull().sum())

# Check the data types of each column
print("\nData types of each column:")
display(train_df.dtypes)

# Select numerical and categorical columns
numerical_cols = train_df.select_dtypes(include=[np.number]).columns
categorical_cols = train_df.select_dtypes(exclude=[np.number]).columns

# Display the number of unique values in categorical columns
print("\nNumber of unique values in categorical columns:")
display(train_df[categorical_cols].nunique())

# Plot the distribution of numerical columns
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(3, 4, i)
    sns.histplot(train_df[col], kde=True)
    plt.title(col)
plt.tight_layout()
plt.show()

# Plot the correlation matrix for numerical columns
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numerical_cols].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

First 5 rows of the dataset:

      id  clonesize  honeybee  ...  fruitmass      seeds       yield
0    245       25.0      0.50  ...   0.399724  29.742583  4177.01520
1   3017       12.5      0.25  ...   0.376874  27.735098  3238.02815
2   8047       12.5      0.25  ...   0.488569  40.655498  7451.72563
3  14223       12.5      0.25  ...   0.466671  37.966864  6580.39696
4  13397       25.0      0.50  ...   0.453650  36.600113  6019.26248

[5 rows x 18 columns]

Summary of the dataset:

                 id     clonesize  ...         seeds         yield
count  12231.000000  12231.000000  ...  12231.000000  12231.000000
mean    7655.390074     19.694628  ...     36.193681   6030.165882
std     4421.960747      6.562779  ...      4.045115   1339.792879
min        1.000000     10.000000  ...     22.079199   1945.530610
25%     3817.000000     12.500000  ...     33.232449   5126.993180
50%     7641.000000     25.000000  ...     36.047770   6117.475900
75%    11507.500000     25.000000  ...     39.203069   7028.673500
max    15286.000000     40.000000  ...     46.585105   8969.401840

[8 rows x 18 columns]

Missing values in the dataset:

id                      0
clonesize               0
honeybee                0
bumbles                 0
andrena                 0
osmia                   0
MaxOfUpperTRange        0
MinOfUpperTRange        0
AverageOfUpperTRange    0
MaxOfLowerTRange        0
MinOfLowerTRange        0
AverageOfLowerTRange    0
RainingDays             0
AverageRainingDays      0
fruitset                0
fruitmass               0
seeds                   0
yield                   0
dtype: int64

Data types of each column:

id                        int64
clonesize               float64
honeybee                float64
bumbles                 float64
andrena                 float64
osmia                   float64
MaxOfUpperTRange        float64
MinOfUpperTRange        float64
AverageOfUpperTRange    float64
MaxOfLowerTRange        float64
MinOfLowerTRange        float64
AverageOfLowerTRange    float64
RainingDays             float64
AverageRainingDays      float64
fruitset                float64
fruitmass               float64
seeds                   float64
yield                   float64
dtype: object

Number of unique values in categorical columns:

Series([], dtype: float64)

ValueError: num must be an integer with 1 <= num <= 12, not 13

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/wild_blueberry_yield/train.csv'
train_df = pd.read_csv(train_path)

# Display the first few rows of the dataset
print("First 5 rows of the dataset:")
display(train_df.head())

# Display the summary of the dataset
print("\nSummary of the dataset:")
display(train_df.describe())

# Check for missing values
print("\nMissing values in the dataset:")
display(train_df.isnull().sum())

# Check the data types of each column
print("\nData types of each column:")
display(train_df.dtypes)

# Select numerical and categorical columns
numerical_cols = train_df.select_dtypes(include=[np.number]).columns
categorical_cols = train_df.select_dtypes(exclude=[np.number]).columns

# Display the number of unique values in categorical columns
print("\nNumber of unique values in categorical columns:")
display(train_df[categorical_cols].nunique())

# Plot the distribution of numerical columns
num_plots = len(numerical_cols)
num_rows = (num_plots // 4) + (num_plots % 4 > 0)
plt.figure(figsize=(15, 5 * num_rows))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(num_rows, 4, i)
    sns.histplot(train_df[col], kde=True)
    plt.title(col)
plt.tight_layout()
plt.show()

# Plot the correlation matrix for numerical columns
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numerical_cols].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

First 5 rows of the dataset:

      id  clonesize  honeybee  ...  fruitmass      seeds       yield
0    245       25.0      0.50  ...   0.399724  29.742583  4177.01520
1   3017       12.5      0.25  ...   0.376874  27.735098  3238.02815
2   8047       12.5      0.25  ...   0.488569  40.655498  7451.72563
3  14223       12.5      0.25  ...   0.466671  37.966864  6580.39696
4  13397       25.0      0.50  ...   0.453650  36.600113  6019.26248

[5 rows x 18 columns]

Summary of the dataset:

                 id     clonesize  ...         seeds         yield
count  12231.000000  12231.000000  ...  12231.000000  12231.000000
mean    7655.390074     19.694628  ...     36.193681   6030.165882
std     4421.960747      6.562779  ...      4.045115   1339.792879
min        1.000000     10.000000  ...     22.079199   1945.530610
25%     3817.000000     12.500000  ...     33.232449   5126.993180
50%     7641.000000     25.000000  ...     36.047770   6117.475900
75%    11507.500000     25.000000  ...     39.203069   7028.673500
max    15286.000000     40.000000  ...     46.585105   8969.401840

[8 rows x 18 columns]

Missing values in the dataset:

id                      0
clonesize               0
honeybee                0
bumbles                 0
andrena                 0
osmia                   0
MaxOfUpperTRange        0
MinOfUpperTRange        0
AverageOfUpperTRange    0
MaxOfLowerTRange        0
MinOfLowerTRange        0
AverageOfLowerTRange    0
RainingDays             0
AverageRainingDays      0
fruitset                0
fruitmass               0
seeds                   0
yield                   0
dtype: int64

Data types of each column:

id                        int64
clonesize               float64
honeybee                float64
bumbles                 float64
andrena                 float64
osmia                   float64
MaxOfUpperTRange        float64
MinOfUpperTRange        float64
AverageOfUpperTRange    float64
MaxOfLowerTRange        float64
MinOfLowerTRange        float64
AverageOfLowerTRange    float64
RainingDays             float64
AverageRainingDays      float64
fruitset                float64
fruitmass               float64
seeds                   float64
yield                   float64
dtype: object

Number of unique values in categorical columns:

Series([], dtype: float64)

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 10:55:19.598 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': [], 'Numeric': ['id', 'clonesize', 'honeybee', 'bumbles', 'andrena', 'osmia', 'MaxOfUpperTRange', 'MinOfUpperTRange', 'AverageOfUpperTRange', 'MaxOfLowerTRange', 'MinOfLowerTRange', 'AverageOfLowerTRange', 'RainingDays', 'AverageRainingDays', 'fruitset', 'fruitmass', 'seeds', 'yield'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import FillMissingValue, RobustScale
from sklearn.model_selection import train_test_split

# Copy the original DataFrame to avoid modifying it
train_df_copy = train_df.copy()

# Handle missing values
fill_missing = FillMissingValue(features=numerical_cols, strategy='median')
train_df_processed = fill_missing.fit_transform(train_df_copy)

# Scale numerical features using RobustScaler to handle outliers
scale_robust = RobustScale(features=numerical_cols)
train_df_processed = scale_robust.fit_transform(train_df_processed)

# Split the data into features and target
X = train_df_processed.drop(columns=['yield'])
y = train_df_processed['yield']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the first 5 rows of the processed training set
display(X_train.head())
display(y_train.head())

            id  clonesize  honeybee  ...  fruitset  fruitmass     seeds
5453  0.200767        0.0       0.0  ... -0.037855   0.232470  0.096673
4665 -0.425070       -1.0      -1.0  ...  0.848871   0.844581  0.861425
4168 -0.694233       -1.0      -1.0  ...  0.740860   0.729380  0.728848
8344 -0.801898       -1.0      -1.0  ...  0.114654  -0.280361  0.131157
3520  0.126000       -1.0      -1.0  ...  0.431812   0.444207  0.445167

[5 rows x 17 columns]

5453    0.174354
4665    0.764066
4168    0.936254
8344    0.756013
3520    0.333674
Name: yield, dtype: float64

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

column_info = get_column_info(train_df_processed)
print("column_info")
print(column_info)

column_info
{'Category': [], 'Numeric': ['id', 'clonesize', 'honeybee', 'bumbles', 'andrena', 'osmia', 'MaxOfUpperTRange', 'MinOfUpperTRange', 'AverageOfUpperTRange', 'MaxOfLowerTRange', 'MinOfLowerTRange', 'AverageOfLowerTRange', 'RainingDays', 'AverageRainingDays', 'fruitset', 'fruitmass', 'seeds', 'yield'], 'Datetime': [], 'Others': []}

In [6]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV

# Define the model
xgb_model = XGBRegressor(random_state=42)

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='neg_mean_absolute_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on the test set
y_pred = best_model.predict(X_test)

# Calculate MAE
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error on the test set: {mae:.2f}")

Mean Absolute Error on the test set: 0.20