In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/reservation_cancellation/train.csv'
df = pd.read_csv(train_path)

# Display the first few rows of the dataframe
print("First 5 rows of the dataset:")
display(df.head())

# Display the summary of the dataset
print("\nSummary of the dataset:")
display(df.info())

# Display the statistical summary of the dataset
print("\nStatistical summary of the dataset:")
display(df.describe(include='all'))

# Check for missing values
print("\nMissing values in the dataset:")
display(df.isnull().sum())

# Distinguish column types
numeric_features = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = df.select_dtypes(include=[np.object]).columns.tolist()

# Display the number of unique values in categorical features
print("\nNumber of unique values in categorical features:")
display(df[categorical_features].nunique())

# Visualize the distribution of numeric features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numeric_features, 1):
    plt.subplot(3, 4, i)
    sns.histplot(df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Visualize the distribution of categorical features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(categorical_features, 1):
    plt.subplot(3, 4, i)
    sns.countplot(data=df, x=feature)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Check the correlation between numeric features
plt.figure(figsize=(10, 8))
sns.heatmap(df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

First 5 rows of the dataset:

      id  no_of_adults  ...  no_of_special_requests  booking_status
0  15559             2  ...                       2               0
1  32783             2  ...                       1               0
2  11797             3  ...                       0               1
3  39750             2  ...                       1               1
4  28711             2  ...                       0               1

[5 rows x 19 columns]

Summary of the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33674 entries, 0 to 33673
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    33674 non-null  int64
 1   no_of_adults                          33674 non-null  int64
 2   no_of_children                        33674 non-null  int64
 3   no_of_weekend_nights                  33674 non-null  int64
 4   no_of_week_nights                     33674 non-null  int64
 5   type_of_meal_plan                     33674 non-null  int64
 6   required_car_parking_space            33674 non-null  int64
 7   room_type_reserved                    33674 non-null  int64
 8   lead_time                             33674 non-null  int64
 9   arrival_year                          33674 non-null  int64
 10  arrival_month                         33674 non-null  int64
 11  arrival_date                          33674 non-null  int64
 12  market_segment_type                   33674 non-null  int64
 13  repeated_guest                        33674 non-null  int64
 14  no_of_previous_cancellations          33674 non-null  int64
 15  no_of_previous_bookings_not_canceled  33674 non-null  int64
 16  avg_price_per_room                    33674 non-null  float64
 17  no_of_special_requests                33674 non-null  int64
 18  booking_status                        33674 non-null  int64
dtypes: float64(1), int64(18)
memory usage: 4.9 MB

None

Statistical summary of the dataset:

                 id  no_of_adults  ...  no_of_special_requests  booking_status
count  33674.000000  33674.000000  ...            33674.000000    33674.000000
mean   21075.355527      1.919374  ...                0.572667        0.392974
std    12120.816554      0.527116  ...                0.776184        0.488418
min        0.000000      0.000000  ...                0.000000        0.000000
25%    10616.250000      2.000000  ...                0.000000        0.000000
50%    21082.500000      2.000000  ...                0.000000        0.000000
75%    31534.750000      2.000000  ...                1.000000        1.000000
max    42099.000000      4.000000  ...                5.000000        1.000000

[8 rows x 19 columns]

Missing values in the dataset:

id                                      0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

C:\Users\xuyutian\AppData\Local\Temp\ipykernel_34828\401847475.py:28: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  categorical_features = df.select_dtypes(include=[np.object]).columns.tolist()

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/reservation_cancellation/train.csv'
df = pd.read_csv(train_path)

# Display the first few rows of the dataframe
print("First 5 rows of the dataset:")
display(df.head())

# Display the summary of the dataset
print("\nSummary of the dataset:")
display(df.info())

# Display the statistical summary of the dataset
print("\nStatistical summary of the dataset:")
display(df.describe(include='all'))

# Check for missing values
print("\nMissing values in the dataset:")
display(df.isnull().sum())

# Distinguish column types
numeric_features = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = df.select_dtypes(include=[object]).columns.tolist()

# Display the number of unique values in categorical features
print("\nNumber of unique values in categorical features:")
display(df[categorical_features].nunique())

# Visualize the distribution of numeric features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numeric_features, 1):
    plt.subplot(3, 4, i)
    sns.histplot(df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Visualize the distribution of categorical features
if categorical_features:
    plt.figure(figsize=(15, 10))
    for i, feature in enumerate(categorical_features, 1):
        plt.subplot(3, 4, i)
        sns.countplot(data=df, x=feature)
        plt.title(f'Distribution of {feature}')
    plt.tight_layout()
    plt.show()
else:
    print('No categorical features found in the dataset.')

# Check the correlation between numeric features
plt.figure(figsize=(10, 8))
sns.heatmap(df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

First 5 rows of the dataset:

      id  no_of_adults  ...  no_of_special_requests  booking_status
0  15559             2  ...                       2               0
1  32783             2  ...                       1               0
2  11797             3  ...                       0               1
3  39750             2  ...                       1               1
4  28711             2  ...                       0               1

[5 rows x 19 columns]

Summary of the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33674 entries, 0 to 33673
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    33674 non-null  int64
 1   no_of_adults                          33674 non-null  int64
 2   no_of_children                        33674 non-null  int64
 3   no_of_weekend_nights                  33674 non-null  int64
 4   no_of_week_nights                     33674 non-null  int64
 5   type_of_meal_plan                     33674 non-null  int64
 6   required_car_parking_space            33674 non-null  int64
 7   room_type_reserved                    33674 non-null  int64
 8   lead_time                             33674 non-null  int64
 9   arrival_year                          33674 non-null  int64
 10  arrival_month                         33674 non-null  int64
 11  arrival_date                          33674 non-null  int64
 12  market_segment_type                   33674 non-null  int64
 13  repeated_guest                        33674 non-null  int64
 14  no_of_previous_cancellations          33674 non-null  int64
 15  no_of_previous_bookings_not_canceled  33674 non-null  int64
 16  avg_price_per_room                    33674 non-null  float64
 17  no_of_special_requests                33674 non-null  int64
 18  booking_status                        33674 non-null  int64
dtypes: float64(1), int64(18)
memory usage: 4.9 MB

None

Statistical summary of the dataset:

                 id  no_of_adults  ...  no_of_special_requests  booking_status
count  33674.000000  33674.000000  ...            33674.000000    33674.000000
mean   21075.355527      1.919374  ...                0.572667        0.392974
std    12120.816554      0.527116  ...                0.776184        0.488418
min        0.000000      0.000000  ...                0.000000        0.000000
25%    10616.250000      2.000000  ...                0.000000        0.000000
50%    21082.500000      2.000000  ...                0.000000        0.000000
75%    31534.750000      2.000000  ...                1.000000        1.000000
max    42099.000000      4.000000  ...                5.000000        1.000000

[8 rows x 19 columns]

Missing values in the dataset:

id                                      0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

Number of unique values in categorical features:

Series([], dtype: float64)

ValueError: num must be an integer with 1 <= num <= 12, not 13

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/reservation_cancellation/train.csv'
df = pd.read_csv(train_path)

# Display the first few rows of the dataframe
print("First 5 rows of the dataset:")
display(df.head())

# Display the summary of the dataset
print("\nSummary of the dataset:")
display(df.info())

# Display the statistical summary of the dataset
print("\nStatistical summary of the dataset:")
display(df.describe(include='all'))

# Check for missing values
print("\nMissing values in the dataset:")
display(df.isnull().sum())

# Distinguish column types
numeric_features = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = df.select_dtypes(include=[object]).columns.tolist()

# Display the number of unique values in categorical features
print("\nNumber of unique values in categorical features:")
display(df[categorical_features].nunique())

# Visualize the distribution of numeric features
num_numeric_features = len(numeric_features)
rows = (num_numeric_features // 4) + (num_numeric_features % 4 > 0)
plt.figure(figsize=(15, 5 * rows))
for i, feature in enumerate(numeric_features, 1):
    plt.subplot(rows, 4, i)
    sns.histplot(df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Visualize the distribution of categorical features
if categorical_features:
    num_categorical_features = len(categorical_features)
    rows = (num_categorical_features // 4) + (num_categorical_features % 4 > 0)
    plt.figure(figsize=(15, 5 * rows))
    for i, feature in enumerate(categorical_features, 1):
        plt.subplot(rows, 4, i)
        sns.countplot(data=df, x=feature)
        plt.title(f'Distribution of {feature}')
    plt.tight_layout()
    plt.show()
else:
    print('No categorical features found in the dataset.')

# Check the correlation between numeric features
plt.figure(figsize=(10, 8))
sns.heatmap(df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

First 5 rows of the dataset:

      id  no_of_adults  ...  no_of_special_requests  booking_status
0  15559             2  ...                       2               0
1  32783             2  ...                       1               0
2  11797             3  ...                       0               1
3  39750             2  ...                       1               1
4  28711             2  ...                       0               1

[5 rows x 19 columns]

Summary of the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33674 entries, 0 to 33673
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    33674 non-null  int64
 1   no_of_adults                          33674 non-null  int64
 2   no_of_children                        33674 non-null  int64
 3   no_of_weekend_nights                  33674 non-null  int64
 4   no_of_week_nights                     33674 non-null  int64
 5   type_of_meal_plan                     33674 non-null  int64
 6   required_car_parking_space            33674 non-null  int64
 7   room_type_reserved                    33674 non-null  int64
 8   lead_time                             33674 non-null  int64
 9   arrival_year                          33674 non-null  int64
 10  arrival_month                         33674 non-null  int64
 11  arrival_date                          33674 non-null  int64
 12  market_segment_type                   33674 non-null  int64
 13  repeated_guest                        33674 non-null  int64
 14  no_of_previous_cancellations          33674 non-null  int64
 15  no_of_previous_bookings_not_canceled  33674 non-null  int64
 16  avg_price_per_room                    33674 non-null  float64
 17  no_of_special_requests                33674 non-null  int64
 18  booking_status                        33674 non-null  int64
dtypes: float64(1), int64(18)
memory usage: 4.9 MB

None

Statistical summary of the dataset:

                 id  no_of_adults  ...  no_of_special_requests  booking_status
count  33674.000000  33674.000000  ...            33674.000000    33674.000000
mean   21075.355527      1.919374  ...                0.572667        0.392974
std    12120.816554      0.527116  ...                0.776184        0.488418
min        0.000000      0.000000  ...                0.000000        0.000000
25%    10616.250000      2.000000  ...                0.000000        0.000000
50%    21082.500000      2.000000  ...                0.000000        0.000000
75%    31534.750000      2.000000  ...                1.000000        1.000000
max    42099.000000      4.000000  ...                5.000000        1.000000

[8 rows x 19 columns]

Missing values in the dataset:

id                                      0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

Number of unique values in categorical features:

Series([], dtype: float64)

No categorical features found in the dataset.

In [4]:
from metagpt.tools.libs.data_preprocess import get_column_info

column_info = get_column_info(df)
print("column_info")
print(column_info)

2025-08-30 20:28:57.396 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': [], 'Numeric': ['id', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space', 'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month', 'arrival_date', 'market_segment_type', 'repeated_guest', 'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests', 'booking_status'], 'Datetime': [], 'Others': []}

In [5]:
from metagpt.tools.libs.data_preprocess import FillMissingValue, StandardScale

# Copy the DataFrame to avoid modifying the original data
df_copy = df.copy()

# Handling missing values
# Since there are no missing values in the dataset, this step is not necessary.
# However, if there were, we would use the FillMissingValue tool to handle them.
# For example, for numeric features, we can use the mean strategy:
# fill_missing = FillMissingValue(numeric_features, strategy='mean')
# df_copy = fill_missing.fit_transform(df_copy)

# Scaling numerical features
# We will use StandardScale to scale the numerical features
scaler = StandardScale(numeric_features)
df_copy = scaler.fit_transform(df_copy)

# Display the first 5 rows of the preprocessed dataset
display(df_copy.head())

         id  no_of_adults  ...  no_of_special_requests  booking_status
0 -0.455121      0.152959  ...                1.838938       -0.804596
1  0.965927      0.152959  ...                0.550564       -0.804596
2 -0.765501      2.050101  ...               -0.737810        1.242859
3  1.540731      0.152959  ...                0.550564        1.242859
4  0.629971      0.152959  ...               -0.737810        1.242859

[5 rows x 19 columns]

In [6]:
from metagpt.tools.libs.data_preprocess import get_column_info

column_info = get_column_info(df_copy)
print("column_info")
print(column_info)

column_info
{'Category': [], 'Numeric': ['id', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space', 'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month', 'arrival_date', 'market_segment_type', 'repeated_guest', 'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests', 'booking_status'], 'Datetime': [], 'Others': []}

In [7]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
from metagpt.tools.libs.data_preprocess import LabelEncode

# Since there are no categorical features, we don't need to perform label encoding.
# However, if there were any, we would use the LabelEncode tool as follows:
# label_encoder = LabelEncode(categorical_features)
# df_copy = label_encoder.fit_transform(df_copy)

# Split the data into features and target
X = df_copy.drop(columns=['id', 'booking_status'])
y = df_copy['booking_status']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the XGBoost classifier
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, scoring='roc_auc', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict probabilities on the test set
y_pred_proba = best_model.predict_proba(X_test)[:, 1]

# Calculate the AUC-ROC score
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC Score: {auc_roc:.4f}")

ValueError:
All the 324 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
324 fits failed with the following error:
Traceback (most recent call last):
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\sklearn.py", line 1491, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got [-0.8045964   1.24285915]