In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/monster/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/monster/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Descriptive statistics
print("Descriptive statistics for Training Data:")
display(train_df.describe(include='all'))

# Distinguish column types
numeric_features = train_df.select_dtypes(include=[np.number]).columns
categorical_features = train_df.select_dtypes(include=[np.object]).columns

# Visualize the distribution of numeric features
for feature in numeric_features:
    plt.figure(figsize=(10, 6))
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
    plt.show()

# Visualize the distribution of categorical features
for feature in categorical_features:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=train_df, x=feature)
    plt.title(f'Distribution of {feature}')
    plt.xticks(rotation=45)
    plt.show()

# Check the correlation matrix for numeric features
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

Training Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  472     0.681615       0.529227     0.625242  white   Ghoul
1  170     0.480836       0.407930     0.539005  clear  Goblin
2  189     0.375197       0.742953     0.320764   blue   Ghost
3  861     0.626017       0.172182     0.408422   blue   Ghoul
4   30     0.250770       0.246258     0.554654  black   Ghost

Testing Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  779     0.516004       0.527508     0.354857  white   Ghoul
1   72     0.523729       0.318483     0.330146  green  Goblin
2   29     0.500197       0.438418     0.532530  clear   Ghoul
3  745     0.417300       0.377595     0.541834  clear  Goblin
4  119     0.515275       0.582627     0.568721  clear  Goblin

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             296 non-null    int64
 1   bone_length    296 non-null    float64
 2   rotting_flesh  296 non-null    float64
 3   hair_length    296 non-null    float64
 4   color          296 non-null    object
 5   type           296 non-null    object
dtypes: float64(3), int64(1), object(2)
memory usage: 14.0+ KB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             75 non-null     int64
 1   bone_length    75 non-null     float64
 2   rotting_flesh  75 non-null     float64
 3   hair_length    75 non-null     float64
 4   color          75 non-null     object
 5   type           75 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 3.6+ KB
Missing values in Training Data:
id               0
bone_length      0
rotting_flesh    0
hair_length      0
color            0
type             0
dtype: int64
Missing values in Testing Data:
id               0
bone_length      0
rotting_flesh    0
hair_length      0
color            0
type             0
dtype: int64
Descriptive statistics for Training Data:

                id  bone_length  rotting_flesh  hair_length  color    type
count   296.000000   296.000000     296.000000   296.000000    296     296
unique         NaN          NaN            NaN          NaN      6       3
top            NaN          NaN            NaN          NaN  white  Goblin
freq           NaN          NaN            NaN          NaN    115     103
mean    453.574324     0.433147       0.513055     0.525371    NaN     NaN
std     260.512340     0.131557       0.151270     0.172703    NaN     NaN
min       1.000000     0.061032       0.172182     0.134600    NaN     NaN
25%     223.500000     0.341046       0.415538     0.393213    NaN     NaN
50%     465.500000     0.430993       0.507979     0.537197    NaN     NaN
75%     680.500000     0.516576       0.615999     0.645414    NaN     NaN
max     897.000000     0.817001       0.932466     1.000000    NaN     NaN

C:\Users\xuyutian\AppData\Local\Temp\ipykernel_8784\1965692920.py:37: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  categorical_features = train_df.select_dtypes(include=[np.object]).columns

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/monster/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/monster/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Descriptive statistics
print("Descriptive statistics for Training Data:")
display(train_df.describe(include='all'))

# Distinguish column types
numeric_features = train_df.select_dtypes(include=[np.number]).columns
categorical_features = train_df.select_dtypes(include=[object]).columns

# Visualize the distribution of numeric features
for feature in numeric_features:
    plt.figure(figsize=(10, 6))
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
    plt.show()

# Visualize the distribution of categorical features
for feature in categorical_features:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=train_df, x=feature)
    plt.title(f'Distribution of {feature}')
    plt.xticks(rotation=45)
    plt.show()

# Check the correlation matrix for numeric features
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

Training Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  472     0.681615       0.529227     0.625242  white   Ghoul
1  170     0.480836       0.407930     0.539005  clear  Goblin
2  189     0.375197       0.742953     0.320764   blue   Ghost
3  861     0.626017       0.172182     0.408422   blue   Ghoul
4   30     0.250770       0.246258     0.554654  black   Ghost

Testing Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  779     0.516004       0.527508     0.354857  white   Ghoul
1   72     0.523729       0.318483     0.330146  green  Goblin
2   29     0.500197       0.438418     0.532530  clear   Ghoul
3  745     0.417300       0.377595     0.541834  clear  Goblin
4  119     0.515275       0.582627     0.568721  clear  Goblin

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             296 non-null    int64
 1   bone_length    296 non-null    float64
 2   rotting_flesh  296 non-null    float64
 3   hair_length    296 non-null    float64
 4   color          296 non-null    object
 5   type           296 non-null    object
dtypes: float64(3), int64(1), object(2)
memory usage: 14.0+ KB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             75 non-null     int64
 1   bone_length    75 non-null     float64
 2   rotting_flesh  75 non-null     float64
 3   hair_length    75 non-null     float64
 4   color          75 non-null     object
 5   type           75 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 3.6+ KB
Missing values in Training Data:
id               0
bone_length      0
rotting_flesh    0
hair_length      0
color            0
type             0
dtype: int64
Missing values in Testing Data:
id               0
bone_length      0
rotting_flesh    0
hair_length      0
color            0
type             0
dtype: int64
Descriptive statistics for Training Data:

                id  bone_length  rotting_flesh  hair_length  color    type
count   296.000000   296.000000     296.000000   296.000000    296     296
unique         NaN          NaN            NaN          NaN      6       3
top            NaN          NaN            NaN          NaN  white  Goblin
freq           NaN          NaN            NaN          NaN    115     103
mean    453.574324     0.433147       0.513055     0.525371    NaN     NaN
std     260.512340     0.131557       0.151270     0.172703    NaN     NaN
min       1.000000     0.061032       0.172182     0.134600    NaN     NaN
25%     223.500000     0.341046       0.415538     0.393213    NaN     NaN
50%     465.500000     0.430993       0.507979     0.537197    NaN     NaN
75%     680.500000     0.516576       0.615999     0.645414    NaN     NaN
max     897.000000     0.817001       0.932466     1.000000    NaN     NaN

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using train_df for the column information
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 13:13:44.516 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': ['color', 'type'], 'Numeric': ['id', 'bone_length', 'rotting_flesh', 'hair_length'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import LabelEncode, StandardScale

# Copy the datasets to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# Encode categorical variables
categorical_features = ['color']
label_encoder = LabelEncode(features=categorical_features)
train_df_encoded = label_encoder.fit_transform(train_df_copy)
test_df_encoded = label_encoder.transform(test_df_copy)

# Scale numeric features
numeric_features = ['bone_length', 'rotting_flesh', 'hair_length']
scaler = StandardScale(features=numeric_features)
train_df_scaled = scaler.fit_transform(train_df_encoded)
test_df_scaled = scaler.transform(test_df_encoded)

# Display the first few rows of the preprocessed datasets
print("Preprocessed Training Data:")
display(train_df_scaled.head())
print("Preprocessed Testing Data:")
display(test_df_scaled.head())

Preprocessed Training Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  472     1.891869       0.107095     0.579263      6   Ghoul
1  170     0.363108      -0.696121     0.079077      3  Goblin
2  189    -0.441246       1.522363    -1.186733      2   Ghost
3  861     1.468536      -2.257217    -0.678313      2   Ghoul
4   30    -1.388649      -1.766698     0.169847      0   Ghost

Preprocessed Testing Data:

    id  bone_length  rotting_flesh  hair_length  color    type
0  779     0.630880       0.095709    -0.988991      6   Ghoul
1   72     0.689698      -1.288431    -1.132321      4  Goblin
2   29     0.510522      -0.494233     0.041523      3   Ghoul
3  745    -0.120664      -0.896998     0.095487      3  Goblin
4  119     0.625331       0.460702     0.251436      3  Goblin

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the preprocessed training data DataFrame
df = train_df_scaled
column_info = get_column_info(df)
print("column_info")
print(column_info)

column_info
{'Category': ['type'], 'Numeric': ['id', 'bone_length', 'rotting_flesh', 'hair_length', 'color'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

# Prepare the data
X_train = train_df_scaled.drop(['id', 'type'], axis=1)
y_train = train_df_scaled['type']
X_test = test_df_scaled.drop(['id', 'type'], axis=1)
y_test = test_df_scaled['type']

# Initialize the model
model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.1, 0.2]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on the test set
y_pred = best_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")

# Save the predictions
test_df_scaled['predicted_type'] = y_pred
test_df_scaled[['id', 'predicted_type']].to_csv('monster_predictions.csv', index=False)

ValueError:
All the 135 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
  File "D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\sklearn.py", line 1491, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['Ghost' 'Ghoul' 'Goblin']

In [7]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# Label encode the 'type' column
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Prepare the data
X_train = train_df_scaled.drop(['id', 'type'], axis=1)
y_train = y_train_encoded
X_test = test_df_scaled.drop(['id', 'type'], axis=1)
y_test = y_test_encoded

# Initialize the model
model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.1, 0.2]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on the test set
y_pred = best_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")

# Save the predictions
test_df_scaled['predicted_type'] = label_encoder.inverse_transform(y_pred)
test_df_scaled[['id', 'predicted_type']].to_csv('monster_predictions.csv', index=False)

Test Accuracy: 0.6133

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py:158: UserWarning: [13:15:11] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)