In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\08_santander_value\\split_train.csv')
eval_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\08_santander_value\\split_eval.csv')

# Display the first few rows of the train and eval datasets
print("Train Data:")
display(train_data.head())
print("Eval Data:")
display(eval_data.head())

# Check the information of the datasets
print("Train Data Info:")
train_data.info()
print("Eval Data Info:")
eval_data.info()

# Check for missing values
print("Missing values in Train Data:")
print(train_data.isnull().sum())
print("Missing values in Eval Data:")
print(eval_data.isnull().sum())

# Summary statistics
print("Summary Statistics for Train Data:")
display(train_data.describe(include='all'))
print("Summary Statistics for Eval Data:")
display(eval_data.describe(include='all'))

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.histplot(train_data['target'], kde=True)
plt.title('Distribution of Target Variable in Train Data')
plt.show()

# Correlation matrix for numerical features
numeric_features = train_data.select_dtypes(include=[np.number]).columns
corr_matrix = train_data[numeric_features].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix for Numerical Features in Train Data')
plt.show()

# Distribution of categorical features
categorical_features = train_data.select_dtypes(include=[np.object]).columns
for feature in categorical_features:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=train_data, x=feature)
    plt.title(f'Distribution of {feature} in Train Data')
    plt.show()

Train Data:

        target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  10666666.66        0.0          0  ...        0.0          0        0.0
1   4000000.00        0.0          0  ...        0.0          0        0.0
2    900000.00        0.0          0  ...        0.0          0        0.0
3   2001000.00        0.0          0  ...        0.0          0        0.0
4  24000000.00        0.0          0  ...        0.0          0        0.0

[5 rows x 19 columns]

Eval Data:

      target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  8018000.0        0.0          0  ...        0.0          0        0.0
1  5000000.0        0.0          0  ...        0.0          0        0.0
2   200000.0        0.0          0  ...        0.0          0        0.0
3  5000000.0        0.0          0  ...        0.0          0        0.0
4   366000.0        0.0          0  ...        0.0          0        0.0

[5 rows x 19 columns]

Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3567 entries, 0 to 3566
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   target      3567 non-null   float64
 1   48df886f9   3567 non-null   float64
 2   0deb4b6a8   3567 non-null   int64
 3   34b15f335   3567 non-null   float64
 4   a8cb14b00   3567 non-null   int64
 5   2f0771a37   3567 non-null   int64
 6   s30347e683  3567 non-null   int64
 7   d08d1fbe3   3567 non-null   int64
 8   6ee66e115   3567 non-null   int64
 9   20aa07010   3567 non-null   float64
 10  dc5a8f1d8   3567 non-null   float64
 11  11d86fa6a   3567 non-null   float64
 12  77c9823f2   3567 non-null   int64
 13  8d6c2a0b2   3567 non-null   int64
 14  4681de4fd   3567 non-null   int64
 15  adf119b9a   3567 non-null   int64
 16  cff75dd09   3567 non-null   float64
 17  96f83a237   3567 non-null   int64
 18  b8a716ebf   3567 non-null   float64
dtypes: float64(8), int64(11)
memory usage: 529.6 KB
Eval Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   target      892 non-null    float64
 1   48df886f9   892 non-null    float64
 2   0deb4b6a8   892 non-null    int64
 3   34b15f335   892 non-null    float64
 4   a8cb14b00   892 non-null    int64
 5   2f0771a37   892 non-null    int64
 6   s30347e683  892 non-null    int64
 7   d08d1fbe3   892 non-null    int64
 8   6ee66e115   892 non-null    int64
 9   20aa07010   892 non-null    float64
 10  dc5a8f1d8   892 non-null    float64
 11  11d86fa6a   892 non-null    float64
 12  77c9823f2   892 non-null    int64
 13  8d6c2a0b2   892 non-null    int64
 14  4681de4fd   892 non-null    int64
 15  adf119b9a   892 non-null    int64
 16  cff75dd09   892 non-null    float64
 17  96f83a237   892 non-null    int64
 18  b8a716ebf   892 non-null    float64
dtypes: float64(8), int64(11)
memory usage: 132.5 KB
Missing values in Train Data:
target        0
48df886f9     0
0deb4b6a8     0
34b15f335     0
a8cb14b00     0
2f0771a37     0
s30347e683    0
d08d1fbe3     0
6ee66e115     0
20aa07010     0
dc5a8f1d8     0
11d86fa6a     0
77c9823f2     0
8d6c2a0b2     0
4681de4fd     0
adf119b9a     0
cff75dd09     0
96f83a237     0
b8a716ebf     0
dtype: int64
Missing values in Eval Data:
target        0
48df886f9     0
0deb4b6a8     0
34b15f335     0
a8cb14b00     0
2f0771a37     0
s30347e683    0
d08d1fbe3     0
6ee66e115     0
20aa07010     0
dc5a8f1d8     0
11d86fa6a     0
77c9823f2     0
8d6c2a0b2     0
4681de4fd     0
adf119b9a     0
cff75dd09     0
96f83a237     0
b8a716ebf     0
dtype: int64
Summary Statistics for Train Data:

             target     48df886f9  ...     96f83a237     b8a716ebf
count  3.567000e+03  3.567000e+03  ...  3.567000e+03  3.567000e+03
mean   5.964817e+06  1.171115e+04  ...  2.841923e+04  4.183609e+05
std    8.229457e+06  3.845407e+05  ...  6.965781e+05  3.415986e+06
min    3.000000e+04  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    6.000000e+05  0.000000e+00  ...  0.000000e+00  0.000000e+00
50%    2.305111e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
75%    8.000000e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
max    4.000000e+07  2.000000e+07  ...  3.600000e+07  1.000000e+08

[8 rows x 19 columns]

Summary Statistics for Eval Data:

             target     48df886f9  ...     96f83a237     b8a716ebf
count  8.920000e+02  8.920000e+02  ...  8.920000e+02  8.920000e+02
mean   5.865372e+06  2.642676e+04  ...  1.088789e+05  3.110610e+05
std    8.257840e+06  4.079306e+05  ...  2.689317e+06  2.398987e+06
min    3.000000e+04  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    6.000000e+05  0.000000e+00  ...  0.000000e+00  0.000000e+00
50%    2.042167e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
75%    7.495500e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
max    4.000000e+07  1.000000e+07  ...  7.960000e+07  3.190000e+07

[8 rows x 19 columns]

C:\Users\xuyutian\AppData\Local\Temp\ipykernel_11196\2622942555.py:49: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  categorical_features = train_data.select_dtypes(include=[np.object]).columns

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\08_santander_value\\split_train.csv')
eval_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\08_santander_value\\split_eval.csv')

# Display the first few rows of the train and eval datasets
print("Train Data:")
display(train_data.head())
print("Eval Data:")
display(eval_data.head())

# Check the information of the datasets
print("Train Data Info:")
train_data.info()
print("Eval Data Info:")
eval_data.info()

# Check for missing values
print("Missing values in Train Data:")
print(train_data.isnull().sum())
print("Missing values in Eval Data:")
print(eval_data.isnull().sum())

# Summary statistics
print("Summary Statistics for Train Data:")
display(train_data.describe(include='all'))
print("Summary Statistics for Eval Data:")
display(eval_data.describe(include='all'))

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.histplot(train_data['target'], kde=True)
plt.title('Distribution of Target Variable in Train Data')
plt.show()

# Correlation matrix for numerical features
numeric_features = train_data.select_dtypes(include=[np.number]).columns
corr_matrix = train_data[numeric_features].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix for Numerical Features in Train Data')
plt.show()

# Distribution of categorical features
categorical_features = train_data.select_dtypes(include=[object]).columns
if len(categorical_features) > 0:
    for feature in categorical_features:
        plt.figure(figsize=(10, 6))
        sns.countplot(data=train_data, x=feature)
        plt.title(f'Distribution of {feature} in Train Data')
        plt.show()
else:
    print('No categorical features found in the train data.')

Train Data:

        target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  10666666.66        0.0          0  ...        0.0          0        0.0
1   4000000.00        0.0          0  ...        0.0          0        0.0
2    900000.00        0.0          0  ...        0.0          0        0.0
3   2001000.00        0.0          0  ...        0.0          0        0.0
4  24000000.00        0.0          0  ...        0.0          0        0.0

[5 rows x 19 columns]

Eval Data:

      target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  8018000.0        0.0          0  ...        0.0          0        0.0
1  5000000.0        0.0          0  ...        0.0          0        0.0
2   200000.0        0.0          0  ...        0.0          0        0.0
3  5000000.0        0.0          0  ...        0.0          0        0.0
4   366000.0        0.0          0  ...        0.0          0        0.0

[5 rows x 19 columns]

Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3567 entries, 0 to 3566
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   target      3567 non-null   float64
 1   48df886f9   3567 non-null   float64
 2   0deb4b6a8   3567 non-null   int64
 3   34b15f335   3567 non-null   float64
 4   a8cb14b00   3567 non-null   int64
 5   2f0771a37   3567 non-null   int64
 6   s30347e683  3567 non-null   int64
 7   d08d1fbe3   3567 non-null   int64
 8   6ee66e115   3567 non-null   int64
 9   20aa07010   3567 non-null   float64
 10  dc5a8f1d8   3567 non-null   float64
 11  11d86fa6a   3567 non-null   float64
 12  77c9823f2   3567 non-null   int64
 13  8d6c2a0b2   3567 non-null   int64
 14  4681de4fd   3567 non-null   int64
 15  adf119b9a   3567 non-null   int64
 16  cff75dd09   3567 non-null   float64
 17  96f83a237   3567 non-null   int64
 18  b8a716ebf   3567 non-null   float64
dtypes: float64(8), int64(11)
memory usage: 529.6 KB
Eval Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   target      892 non-null    float64
 1   48df886f9   892 non-null    float64
 2   0deb4b6a8   892 non-null    int64
 3   34b15f335   892 non-null    float64
 4   a8cb14b00   892 non-null    int64
 5   2f0771a37   892 non-null    int64
 6   s30347e683  892 non-null    int64
 7   d08d1fbe3   892 non-null    int64
 8   6ee66e115   892 non-null    int64
 9   20aa07010   892 non-null    float64
 10  dc5a8f1d8   892 non-null    float64
 11  11d86fa6a   892 non-null    float64
 12  77c9823f2   892 non-null    int64
 13  8d6c2a0b2   892 non-null    int64
 14  4681de4fd   892 non-null    int64
 15  adf119b9a   892 non-null    int64
 16  cff75dd09   892 non-null    float64
 17  96f83a237   892 non-null    int64
 18  b8a716ebf   892 non-null    float64
dtypes: float64(8), int64(11)
memory usage: 132.5 KB
Missing values in Train Data:
target        0
48df886f9     0
0deb4b6a8     0
34b15f335     0
a8cb14b00     0
2f0771a37     0
s30347e683    0
d08d1fbe3     0
6ee66e115     0
20aa07010     0
dc5a8f1d8     0
11d86fa6a     0
77c9823f2     0
8d6c2a0b2     0
4681de4fd     0
adf119b9a     0
cff75dd09     0
96f83a237     0
b8a716ebf     0
dtype: int64
Missing values in Eval Data:
target        0
48df886f9     0
0deb4b6a8     0
34b15f335     0
a8cb14b00     0
2f0771a37     0
s30347e683    0
d08d1fbe3     0
6ee66e115     0
20aa07010     0
dc5a8f1d8     0
11d86fa6a     0
77c9823f2     0
8d6c2a0b2     0
4681de4fd     0
adf119b9a     0
cff75dd09     0
96f83a237     0
b8a716ebf     0
dtype: int64
Summary Statistics for Train Data:

             target     48df886f9  ...     96f83a237     b8a716ebf
count  3.567000e+03  3.567000e+03  ...  3.567000e+03  3.567000e+03
mean   5.964817e+06  1.171115e+04  ...  2.841923e+04  4.183609e+05
std    8.229457e+06  3.845407e+05  ...  6.965781e+05  3.415986e+06
min    3.000000e+04  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    6.000000e+05  0.000000e+00  ...  0.000000e+00  0.000000e+00
50%    2.305111e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
75%    8.000000e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
max    4.000000e+07  2.000000e+07  ...  3.600000e+07  1.000000e+08

[8 rows x 19 columns]

Summary Statistics for Eval Data:

             target     48df886f9  ...     96f83a237     b8a716ebf
count  8.920000e+02  8.920000e+02  ...  8.920000e+02  8.920000e+02
mean   5.865372e+06  2.642676e+04  ...  1.088789e+05  3.110610e+05
std    8.257840e+06  4.079306e+05  ...  2.689317e+06  2.398987e+06
min    3.000000e+04  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    6.000000e+05  0.000000e+00  ...  0.000000e+00  0.000000e+00
50%    2.042167e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
75%    7.495500e+06  0.000000e+00  ...  0.000000e+00  0.000000e+00
max    4.000000e+07  1.000000e+07  ...  7.960000e+07  3.190000e+07

[8 rows x 19 columns]

No categorical features found in the train data.

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_data DataFrame from the finished tasks
column_info = get_column_info(train_data)
print("column_info")
print(column_info)

2025-08-30 17:43:02.962 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': [], 'Numeric': ['target', '48df886f9', '0deb4b6a8', '34b15f335', 'a8cb14b00', '2f0771a37', 's30347e683', 'd08d1fbe3', '6ee66e115', '20aa07010', 'dc5a8f1d8', '11d86fa6a', '77c9823f2', '8d6c2a0b2', '4681de4fd', 'adf119b9a', 'cff75dd09', '96f83a237', 'b8a716ebf'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import FillMissingValue, StandardScale

# Copy the dataframes to avoid modifying the original data
train_data_copy = train_data.copy()
eval_data_copy = eval_data.copy()

# Since there are no missing values, we skip the FillMissingValue step

# Standardize the numerical features (excluding the target column)
numerical_features = [col for col in train_data_copy.columns if col != 'target']
scaler = StandardScale(features=numerical_features)
train_data_scaled = scaler.fit_transform(train_data_copy)
eval_data_scaled = scaler.transform(eval_data_copy)

# Display the first few rows of the scaled data
print("Scaled Train Data:")
display(train_data_scaled.head())
print("Scaled Eval Data:")
display(eval_data_scaled.head())

Scaled Train Data:

        target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  10666666.66  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
1   4000000.00  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
2    900000.00  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
3   2001000.00  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
4  24000000.00  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489

[5 rows x 19 columns]

Scaled Eval Data:

      target  48df886f9  0deb4b6a8  ...  cff75dd09  96f83a237  b8a716ebf
0  8018000.0  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
1  5000000.0  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
2   200000.0  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
3  5000000.0  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489
4   366000.0  -0.030459  -0.020867  ...  -0.050775  -0.040804  -0.122489

[5 rows x 19 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the latest DataFrame from the finished tasks
column_info_train = get_column_info(train_data_scaled)
print("Column Info for Scaled Train Data:")
print(column_info_train)

column_info_eval = get_column_info(eval_data_scaled)
print("Column Info for Scaled Eval Data:")
print(column_info_eval)

Column Info for Scaled Train Data:
{'Category': [], 'Numeric': ['target', '48df886f9', '0deb4b6a8', '34b15f335', 'a8cb14b00', '2f0771a37', 's30347e683', 'd08d1fbe3', '6ee66e115', '20aa07010', 'dc5a8f1d8', '11d86fa6a', '77c9823f2', '8d6c2a0b2', '4681de4fd', 'adf119b9a', 'cff75dd09', '96f83a237', 'b8a716ebf'], 'Datetime': [], 'Others': []}
Column Info for Scaled Eval Data:
{'Category': [], 'Numeric': ['target', '48df886f9', '0deb4b6a8', '34b15f335', 'a8cb14b00', '2f0771a37', 's30347e683', 'd08d1fbe3', '6ee66e115', '20aa07010', 'dc5a8f1d8', '11d86fa6a', '77c9823f2', '8d6c2a0b2', '4681de4fd', 'adf119b9a', 'cff75dd09', '96f83a237', 'b8a716ebf'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_log_error
from xgboost import XGBRegressor

# Split the train data into features and target
X_train = train_data_scaled.drop(columns=['target'])
y_train = train_data_scaled['target']

# Split the eval data into features and target
X_eval = eval_data_scaled.drop(columns=['target'])
y_eval = eval_data_scaled['target']

# Initialize the XGBoost model
xgb_model = XGBRegressor(objective='reg:squarederror', random_state=42)

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Perform grid search to find the best hyperparameters
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_log_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on the eval set
y_pred = best_model.predict(X_eval)

# Calculate RMSLE
rmsle = np.sqrt(mean_squared_log_error(y_eval, y_pred))
print(f"RMSLE on the eval set: {rmsle}")

RMSLE on the eval set: 1.9136218590069167

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\sklearn\model_selection\_search.py:979: UserWarning: One or more of the test scores are non-finite: [-4.21466085 -4.22037084 -4.13719272 -4.13920451 -4.0861077  -4.08240738
 -4.16042598 -4.16144942 -4.06577938 -4.07507218 -4.00744174 -4.01708073
 -4.12298806 -4.12029997 -4.00806558 -4.0095738  -3.94665854 -3.94883377
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
 -4.20795492 -4.20945046 -4.13339574 -4.12983954 -4.0890464  -4.09002059
 -4.14881834 -4.15399941 -4.05811091 -4.06941306 -4.00750197 -4.01451142
 -4.10803176 -4.10602981 -4.0016097  -4.01321044 -3.94624243 -3.95572106
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan]
  warnings.warn(