In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/smoker_status_Bio_Signals/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/smoker_status_Bio_Signals/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Descriptive statistics
print("Descriptive Statistics for Training Data:")
display(train_df.describe(include='all'))

# Check the distribution of the target variable
print("Distribution of the target variable in Training Data:")
print(train_df['smoker'].value_counts(normalize=True))

# Visualize the distribution of the target variable
plt.figure(figsize=(8, 6))
sns.countplot(x='smoker', data=train_df)
plt.title('Distribution of Smoker Status in Training Data')
plt.show()

# Check the correlation between numerical features
numerical_features = train_df.select_dtypes(include=[np.number]).columns.tolist()
correlation_matrix = train_df[numerical_features].corr()

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

Training Data:

       id  age  height  weight  waist  ...  AST  ALT  Gtp  dental_caries  smoking
0   60700   40     150      50   80.0  ...   14   11    9              0        0
1   44065   65     150      50   69.0  ...   17   24   25              0        0
2   39538   55     155      55   80.0  ...   19   15   16              0        0
3  105427   55     160      60   83.0  ...   14   13   26              0        0
4  148669   30     180      90   95.0  ...   25   30   21              0        0

[5 rows x 24 columns]

Testing Data:

       id  age  height  weight  waist  ...  AST  ALT  Gtp  dental_caries  smoking
0  145654   35     175      80   84.0  ...   31   22   32              0        1
1   49118   35     185      80   88.0  ...   22   22   17              0        1
2   21769   20     160      60   76.0  ...   24   32   41              1        1
3  108299   60     155      60   87.8  ...   21   16   14              0        0
4  117130   60     165      70   85.0  ...   27   40   61              0        0

[5 rows x 24 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127404 entries, 0 to 127403
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   127404 non-null  int64
 1   age                  127404 non-null  int64
 2   height               127404 non-null  int64
 3   weight               127404 non-null  int64
 4   waist                127404 non-null  float64
 5   eyesight_left        127404 non-null  float64
 6   eyesight_right       127404 non-null  float64
 7   hearing_left         127404 non-null  int64
 8   hearing_right        127404 non-null  int64
 9   systolic             127404 non-null  int64
 10  relaxation           127404 non-null  int64
 11  fasting_blood_sugar  127404 non-null  int64
 12  Cholesterol          127404 non-null  int64
 13  triglyceride         127404 non-null  int64
 14  HDL                  127404 non-null  int64
 15  LDL                  127404 non-null  int64
 16  hemoglobin           127404 non-null  float64
 17  Urine_protein        127404 non-null  int64
 18  serum_creatinine     127404 non-null  float64
 19  AST                  127404 non-null  int64
 20  ALT                  127404 non-null  int64
 21  Gtp                  127404 non-null  int64
 22  dental_caries        127404 non-null  int64
 23  smoking              127404 non-null  int64
dtypes: float64(5), int64(19)
memory usage: 23.3 MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31852 entries, 0 to 31851
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   31852 non-null  int64
 1   age                  31852 non-null  int64
 2   height               31852 non-null  int64
 3   weight               31852 non-null  int64
 4   waist                31852 non-null  float64
 5   eyesight_left        31852 non-null  float64
 6   eyesight_right       31852 non-null  float64
 7   hearing_left         31852 non-null  int64
 8   hearing_right        31852 non-null  int64
 9   systolic             31852 non-null  int64
 10  relaxation           31852 non-null  int64
 11  fasting_blood_sugar  31852 non-null  int64
 12  Cholesterol          31852 non-null  int64
 13  triglyceride         31852 non-null  int64
 14  HDL                  31852 non-null  int64
 15  LDL                  31852 non-null  int64
 16  hemoglobin           31852 non-null  float64
 17  Urine_protein        31852 non-null  int64
 18  serum_creatinine     31852 non-null  float64
 19  AST                  31852 non-null  int64
 20  ALT                  31852 non-null  int64
 21  Gtp                  31852 non-null  int64
 22  dental_caries        31852 non-null  int64
 23  smoking              31852 non-null  int64
dtypes: float64(5), int64(19)
memory usage: 5.8 MB
Missing values in Training Data:
id                     0
age                    0
height                 0
weight                 0
waist                  0
eyesight_left          0
eyesight_right         0
hearing_left           0
hearing_right          0
systolic               0
relaxation             0
fasting_blood_sugar    0
Cholesterol            0
triglyceride           0
HDL                    0
LDL                    0
hemoglobin             0
Urine_protein          0
serum_creatinine       0
AST                    0
ALT                    0
Gtp                    0
dental_caries          0
smoking                0
dtype: int64
Missing values in Testing Data:
id                     0
age                    0
height                 0
weight                 0
waist                  0
eyesight_left          0
eyesight_right         0
hearing_left           0
hearing_right          0
systolic               0
relaxation             0
fasting_blood_sugar    0
Cholesterol            0
triglyceride           0
HDL                    0
LDL                    0
hemoglobin             0
Urine_protein          0
serum_creatinine       0
AST                    0
ALT                    0
Gtp                    0
dental_caries          0
smoking                0
dtype: int64
Descriptive Statistics for Training Data:

                  id            age  ...  dental_caries        smoking
count  127404.000000  127404.000000  ...  127404.000000  127404.000000
mean    79470.262802      44.301929  ...       0.198353       0.436281
std     46005.660395      11.826195  ...       0.398761       0.495925
min         1.000000      20.000000  ...       0.000000       0.000000
25%     39568.250000      40.000000  ...       0.000000       0.000000
50%     79443.500000      40.000000  ...       0.000000       0.000000
75%    119336.250000      55.000000  ...       0.000000       1.000000
max    159254.000000      85.000000  ...       1.000000       1.000000

[8 rows x 24 columns]

Distribution of the target variable in Training Data:

KeyError: 'smoker'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/smoker_status_Bio_Signals/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/smoker_status_Bio_Signals/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print('Training Data:')
display(train_df.head())
print('Testing Data:')
display(test_df.head())

# Check the information of the datasets
print('Training Data Info:')
train_df.info()
print('Testing Data Info:')
test_df.info()

# Check for missing values
print('Missing values in Training Data:')
print(train_df.isnull().sum())
print('Missing values in Testing Data:')
print(test_df.isnull().sum())

# Descriptive statistics
print('Descriptive Statistics for Training Data:')
display(train_df.describe(include='all'))

# Check the distribution of the target variable
print('Distribution of the target variable in Training Data:')
print(train_df['smoking'].value_counts(normalize=True))

# Visualize the distribution of the target variable
plt.figure(figsize=(8, 6))
sns.countplot(x='smoking', data=train_df)
plt.title('Distribution of Smoker Status in Training Data')
plt.show()

# Check the correlation between numerical features
numerical_features = train_df.select_dtypes(include=[np.number]).columns.tolist()
correlation_matrix = train_df[numerical_features].corr()

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

Training Data:

       id  age  height  weight  waist  ...  AST  ALT  Gtp  dental_caries  smoking
0   60700   40     150      50   80.0  ...   14   11    9              0        0
1   44065   65     150      50   69.0  ...   17   24   25              0        0
2   39538   55     155      55   80.0  ...   19   15   16              0        0
3  105427   55     160      60   83.0  ...   14   13   26              0        0
4  148669   30     180      90   95.0  ...   25   30   21              0        0

[5 rows x 24 columns]

Testing Data:

       id  age  height  weight  waist  ...  AST  ALT  Gtp  dental_caries  smoking
0  145654   35     175      80   84.0  ...   31   22   32              0        1
1   49118   35     185      80   88.0  ...   22   22   17              0        1
2   21769   20     160      60   76.0  ...   24   32   41              1        1
3  108299   60     155      60   87.8  ...   21   16   14              0        0
4  117130   60     165      70   85.0  ...   27   40   61              0        0

[5 rows x 24 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127404 entries, 0 to 127403
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   127404 non-null  int64
 1   age                  127404 non-null  int64
 2   height               127404 non-null  int64
 3   weight               127404 non-null  int64
 4   waist                127404 non-null  float64
 5   eyesight_left        127404 non-null  float64
 6   eyesight_right       127404 non-null  float64
 7   hearing_left         127404 non-null  int64
 8   hearing_right        127404 non-null  int64
 9   systolic             127404 non-null  int64
 10  relaxation           127404 non-null  int64
 11  fasting_blood_sugar  127404 non-null  int64
 12  Cholesterol          127404 non-null  int64
 13  triglyceride         127404 non-null  int64
 14  HDL                  127404 non-null  int64
 15  LDL                  127404 non-null  int64
 16  hemoglobin           127404 non-null  float64
 17  Urine_protein        127404 non-null  int64
 18  serum_creatinine     127404 non-null  float64
 19  AST                  127404 non-null  int64
 20  ALT                  127404 non-null  int64
 21  Gtp                  127404 non-null  int64
 22  dental_caries        127404 non-null  int64
 23  smoking              127404 non-null  int64
dtypes: float64(5), int64(19)
memory usage: 23.3 MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31852 entries, 0 to 31851
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   31852 non-null  int64
 1   age                  31852 non-null  int64
 2   height               31852 non-null  int64
 3   weight               31852 non-null  int64
 4   waist                31852 non-null  float64
 5   eyesight_left        31852 non-null  float64
 6   eyesight_right       31852 non-null  float64
 7   hearing_left         31852 non-null  int64
 8   hearing_right        31852 non-null  int64
 9   systolic             31852 non-null  int64
 10  relaxation           31852 non-null  int64
 11  fasting_blood_sugar  31852 non-null  int64
 12  Cholesterol          31852 non-null  int64
 13  triglyceride         31852 non-null  int64
 14  HDL                  31852 non-null  int64
 15  LDL                  31852 non-null  int64
 16  hemoglobin           31852 non-null  float64
 17  Urine_protein        31852 non-null  int64
 18  serum_creatinine     31852 non-null  float64
 19  AST                  31852 non-null  int64
 20  ALT                  31852 non-null  int64
 21  Gtp                  31852 non-null  int64
 22  dental_caries        31852 non-null  int64
 23  smoking              31852 non-null  int64
dtypes: float64(5), int64(19)
memory usage: 5.8 MB
Missing values in Training Data:
id                     0
age                    0
height                 0
weight                 0
waist                  0
eyesight_left          0
eyesight_right         0
hearing_left           0
hearing_right          0
systolic               0
relaxation             0
fasting_blood_sugar    0
Cholesterol            0
triglyceride           0
HDL                    0
LDL                    0
hemoglobin             0
Urine_protein          0
serum_creatinine       0
AST                    0
ALT                    0
Gtp                    0
dental_caries          0
smoking                0
dtype: int64
Missing values in Testing Data:
id                     0
age                    0
height                 0
weight                 0
waist                  0
eyesight_left          0
eyesight_right         0
hearing_left           0
hearing_right          0
systolic               0
relaxation             0
fasting_blood_sugar    0
Cholesterol            0
triglyceride           0
HDL                    0
LDL                    0
hemoglobin             0
Urine_protein          0
serum_creatinine       0
AST                    0
ALT                    0
Gtp                    0
dental_caries          0
smoking                0
dtype: int64
Descriptive Statistics for Training Data:

                  id            age  ...  dental_caries        smoking
count  127404.000000  127404.000000  ...  127404.000000  127404.000000
mean    79470.262802      44.301929  ...       0.198353       0.436281
std     46005.660395      11.826195  ...       0.398761       0.495925
min         1.000000      20.000000  ...       0.000000       0.000000
25%     39568.250000      40.000000  ...       0.000000       0.000000
50%     79443.500000      40.000000  ...       0.000000       0.000000
75%    119336.250000      55.000000  ...       0.000000       1.000000
max    159254.000000      85.000000  ...       1.000000       1.000000

[8 rows x 24 columns]

Distribution of the target variable in Training Data:
smoking
0    0.563719
1    0.436281
Name: proportion, dtype: float64

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 11:30:14.185 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': [], 'Numeric': ['id', 'age', 'height', 'weight', 'waist', 'eyesight_left', 'eyesight_right', 'hearing_left', 'hearing_right', 'systolic', 'relaxation', 'fasting_blood_sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine_protein', 'serum_creatinine', 'AST', 'ALT', 'Gtp', 'dental_caries', 'smoking'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import FillMissingValue, StandardScale

# Copy the datasets to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# Handling missing values
# Since there are no missing values in the dataset, this step is not necessary.
# However, if there were, we would use the FillMissingValue tool to handle them.
# For example, for numerical features, we can use the mean strategy:
# fill_missing = FillMissingValue(features=numerical_features, strategy='mean')
# train_df_copy = fill_missing.fit_transform(train_df_copy)
# test_df_copy = fill_missing.transform(test_df_copy)

# Standardize numerical features
# We will standardize all numerical features except the target variable 'smoking'
numerical_features = [col for col in train_df_copy.columns if col != 'smoking']
scaler = StandardScale(features=numerical_features)
train_df_copy = scaler.fit_transform(train_df_copy)
test_df_copy = scaler.transform(test_df_copy)

# Display the first few rows of the preprocessed datasets
print('Preprocessed Training Data:')
display(train_df_copy.head())
print('Preprocessed Testing Data:')
display(test_df_copy.head())

Preprocessed Training Data:

         id       age    height  ...       Gtp  dental_caries  smoking
0 -0.408001 -0.363764 -1.729695  ... -0.871202      -0.497426        0
1 -0.769588  1.750195 -1.729695  ... -0.358082      -0.497426        0
2 -0.867989  0.904612 -1.162983  ... -0.646712      -0.497426        0
3  0.564210  0.904612 -0.596270  ... -0.326012      -0.497426        0
4  1.504141 -1.209348  1.670580  ... -0.486362      -0.497426        0

[5 rows x 24 columns]

Preprocessed Testing Data:

         id       age    height  ...       Gtp  dental_caries  smoking
0  1.438606 -0.786556  1.103867  ... -0.133593      -0.497426        1
1 -0.659753 -0.786556  2.237292  ... -0.614642      -0.497426        1
2 -1.254226 -2.054932 -0.596270  ...  0.155037       2.010351        1
3  0.626637  1.327404 -1.162983  ... -0.710852      -0.497426        0
4  0.818592  1.327404 -0.029558  ...  0.796436      -0.497426        0

[5 rows x 24 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the preprocessed training data DataFrame
column_info = get_column_info(train_df_copy)
print("column_info")
print(column_info)

column_info
{'Category': [], 'Numeric': ['id', 'age', 'height', 'weight', 'waist', 'eyesight_left', 'eyesight_right', 'hearing_left', 'hearing_right', 'systolic', 'relaxation', 'fasting_blood_sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine_protein', 'serum_creatinine', 'AST', 'ALT', 'Gtp', 'dental_caries', 'smoking'], 'Datetime': [], 'Others': []}

In [6]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

# Define the features and the target variable
X = train_df_copy.drop(columns=['id', 'smoking'])
y = train_df_copy['smoking']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Define the XGBoost DART model
xgb_model = xgb.XGBClassifier(
    booster='dart',
    learning_rate=0.1,
    n_estimators=1000,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='auc'
)

# Train the model
xgb_model.fit(X_train, y_train, early_stopping_rounds=50, eval_set=[(X_val, y_val)], verbose=100)

# Predict on the test set
X_test = test_df_copy.drop(columns=['id', 'smoking'])
y_test = test_df_copy['smoking']
y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]

# Calculate AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f'AUC-ROC on the test set: {auc_roc:.4f}')

TypeError: XGBClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'

In [7]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score

# Define the features and the target variable
X = train_df_copy.drop(columns=['id', 'smoking'])
y = train_df_copy['smoking']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Convert the data to DMatrix format
train_dmatrix = xgb.DMatrix(X_train, label=y_train)
val_dmatrix = xgb.DMatrix(X_val, label=y_val)
test_dmatrix = xgb.DMatrix(test_df_copy.drop(columns=['id', 'smoking']), label=test_df_copy['smoking'])

# Define the XGBoost parameters
params = {
    'booster': 'dart',
    'learning_rate': 0.1,
    'n_estimators': 1000,
    'max_depth': 6,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'reg_alpha': 0.1,
    'reg_lambda': 0.1,
    'random_state': 42,
    'eval_metric': 'auc'
}

# Train the model with early stopping
xgb_model = xgb.train(
    params=params,
    dtrain=train_dmatrix,
    num_boost_round=1000,
    evals=[(val_dmatrix, 'validate')],
    early_stopping_rounds=50,
    verbose_eval=100
)

# Predict on the test set
y_pred_proba = xgb_model.predict(test_dmatrix)

# Calculate AUC-ROC
auc_roc = roc_auc_score(test_df_copy['smoking'], y_pred_proba)
print(f'AUC-ROC on the test set: {auc_roc:.4f}')

[0]	validate-auc:0.82348

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py:158: UserWarning: [11:31:38] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "n_estimators" } are not used.

  warnings.warn(smsg, UserWarning)

[100]	validate-auc:0.86617

[200]	validate-auc:0.86806

[300]	validate-auc:0.86908

[400]	validate-auc:0.86950

[469]	validate-auc:0.86916

AUC-ROC on the test set: 0.8624