In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\06_santander_customer\\split_train.csv')
eval_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\06_santander_customer\\split_eval.csv')

# Display the first few rows of the train and eval datasets
print("Train Data:")
display(train_data.head())
print("Eval Data:")
display(eval_data.head())

# Check the shape of the datasets
print("Train Data Shape:", train_data.shape)
print("Eval Data Shape:", eval_data.shape)

# Check for missing values
print("Missing values in Train Data:")
print(train_data.isnull().sum())
print("Missing values in Eval Data:")
print(eval_data.isnull().sum())

# Check the data types of the columns
print("Data types in Train Data:")
print(train_data.dtypes)
print("Data types in Eval Data:")
print(eval_data.dtypes)

# Summary statistics for numerical columns
print("Summary statistics for numerical columns in Train Data:")
display(train_data.describe())

# Summary statistics for categorical columns
print("Summary statistics for categorical columns in Train Data:")
display(train_data.describe(include=['O']))

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.countplot(x='target', data=train_data)
plt.title('Distribution of Target Variable')
plt.show()

# Correlation matrix for numerical columns
numerical_features = train_data.select_dtypes(include=[np.number]).columns
correlation_matrix = train_data[numerical_features].corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix for Numerical Features')
plt.show()

Train Data:

   target    var_0   var_1    var_2  ...   var_14   var_15   var_16   var_17
0       0  12.6407  2.9411  15.2365  ...  11.1089  15.0745   4.8570  -3.3979
1       0   5.5300 -2.6867  10.0739  ...   2.8759  13.9574   6.2063   6.6106
2       0   9.3848  1.3839   9.4459  ...  10.4819  14.2421   3.8085 -10.8337
3       0  11.5179 -5.7696  12.4163  ...   6.4419  14.8648   8.5745  -0.7653
4       0  12.6522 -6.0295  12.0836  ...   8.3703  14.4378  11.4569   0.4568

[5 rows x 19 columns]

Eval Data:

   target    var_0   var_1    var_2  ...  var_14   var_15   var_16   var_17
0       1   8.6646 -2.0466  12.2794  ...  6.1990  14.3138  11.9914 -18.2099
1       1  18.2832 -0.0892  10.4312  ...  8.2536  14.2073  10.8528  -2.7252
2       0  13.8916 -0.3960   8.1494  ...  3.6420  14.9770   9.0804 -14.1675
3       0   8.2493 -0.0634  10.6337  ...  8.9594  14.5846   3.3459   2.4677
4       0   9.6026  2.7460   5.8710  ...  7.7771  13.9491  10.4395 -12.0996

[5 rows x 19 columns]

Train Data Shape: (160000, 19)
Eval Data Shape: (40000, 19)
Missing values in Train Data:
target    0
var_0     0
var_1     0
var_2     0
var_3     0
var_4     0
var_5     0
var_6     0
var_7     0
var_8     0
var_9     0
var_10    0
var_11    0
var_12    0
var_13    0
var_14    0
var_15    0
var_16    0
var_17    0
dtype: int64
Missing values in Eval Data:
target    0
var_0     0
var_1     0
var_2     0
var_3     0
var_4     0
var_5     0
var_6     0
var_7     0
var_8     0
var_9     0
var_10    0
var_11    0
var_12    0
var_13    0
var_14    0
var_15    0
var_16    0
var_17    0
dtype: int64
Data types in Train Data:
target      int64
var_0     float64
var_1     float64
var_2     float64
var_3     float64
var_4     float64
var_5     float64
var_6     float64
var_7     float64
var_8     float64
var_9     float64
var_10    float64
var_11    float64
var_12    float64
var_13    float64
var_14    float64
var_15    float64
var_16    float64
var_17    float64
dtype: object
Data types in Eval Data:
target      int64
var_0     float64
var_1     float64
var_2     float64
var_3     float64
var_4     float64
var_5     float64
var_6     float64
var_7     float64
var_8     float64
var_9     float64
var_10    float64
var_11    float64
var_12    float64
var_13    float64
var_14    float64
var_15    float64
var_16    float64
var_17    float64
dtype: object
Summary statistics for numerical columns in Train Data:

              target          var_0  ...         var_16         var_17
count  160000.000000  160000.000000  ...  160000.000000  160000.000000
mean        0.100175      10.677401  ...       9.337185      -5.700292
std         0.300234       3.039160  ...       2.558483       6.715098
min         0.000000       0.408400  ...       0.635100     -33.380200
25%         0.000000       8.452700  ...       7.455175     -10.485750
50%         0.000000      10.524750  ...       9.235850      -5.663200
75%         0.000000      12.759200  ...      11.064625      -0.810775
max         1.000000      20.315000  ...      17.950600      19.025900

[8 rows x 19 columns]

Summary statistics for categorical columns in Train Data:

ValueError: No objects to concatenate

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\06_santander_customer\\split_train.csv')
eval_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\ml_benchmark\\06_santander_customer\\split_eval.csv')

# Display the first few rows of the train and eval datasets
print("Train Data:")
display(train_data.head())
print("Eval Data:")
display(eval_data.head())

# Check the shape of the datasets
print("Train Data Shape:", train_data.shape)
print("Eval Data Shape:", eval_data.shape)

# Check for missing values
print("Missing values in Train Data:")
print(train_data.isnull().sum())
print("Missing values in Eval Data:")
print(eval_data.isnull().sum())

# Check the data types of the columns
print("Data types in Train Data:")
print(train_data.dtypes)
print("Data types in Eval Data:")
print(eval_data.dtypes)

# Summary statistics for numerical columns
print("Summary statistics for numerical columns in Train Data:")
display(train_data.describe())

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.countplot(x='target', data=train_data)
plt.title('Distribution of Target Variable')
plt.show()

# Correlation matrix for numerical columns
numerical_features = train_data.select_dtypes(include=[np.number]).columns
correlation_matrix = train_data[numerical_features].corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix for Numerical Features')
plt.show()

Train Data:

   target    var_0   var_1    var_2  ...   var_14   var_15   var_16   var_17
0       0  12.6407  2.9411  15.2365  ...  11.1089  15.0745   4.8570  -3.3979
1       0   5.5300 -2.6867  10.0739  ...   2.8759  13.9574   6.2063   6.6106
2       0   9.3848  1.3839   9.4459  ...  10.4819  14.2421   3.8085 -10.8337
3       0  11.5179 -5.7696  12.4163  ...   6.4419  14.8648   8.5745  -0.7653
4       0  12.6522 -6.0295  12.0836  ...   8.3703  14.4378  11.4569   0.4568

[5 rows x 19 columns]

Eval Data:

   target    var_0   var_1    var_2  ...  var_14   var_15   var_16   var_17
0       1   8.6646 -2.0466  12.2794  ...  6.1990  14.3138  11.9914 -18.2099
1       1  18.2832 -0.0892  10.4312  ...  8.2536  14.2073  10.8528  -2.7252
2       0  13.8916 -0.3960   8.1494  ...  3.6420  14.9770   9.0804 -14.1675
3       0   8.2493 -0.0634  10.6337  ...  8.9594  14.5846   3.3459   2.4677
4       0   9.6026  2.7460   5.8710  ...  7.7771  13.9491  10.4395 -12.0996

[5 rows x 19 columns]

Train Data Shape: (160000, 19)
Eval Data Shape: (40000, 19)
Missing values in Train Data:
target    0
var_0     0
var_1     0
var_2     0
var_3     0
var_4     0
var_5     0
var_6     0
var_7     0
var_8     0
var_9     0
var_10    0
var_11    0
var_12    0
var_13    0
var_14    0
var_15    0
var_16    0
var_17    0
dtype: int64
Missing values in Eval Data:
target    0
var_0     0
var_1     0
var_2     0
var_3     0
var_4     0
var_5     0
var_6     0
var_7     0
var_8     0
var_9     0
var_10    0
var_11    0
var_12    0
var_13    0
var_14    0
var_15    0
var_16    0
var_17    0
dtype: int64
Data types in Train Data:
target      int64
var_0     float64
var_1     float64
var_2     float64
var_3     float64
var_4     float64
var_5     float64
var_6     float64
var_7     float64
var_8     float64
var_9     float64
var_10    float64
var_11    float64
var_12    float64
var_13    float64
var_14    float64
var_15    float64
var_16    float64
var_17    float64
dtype: object
Data types in Eval Data:
target      int64
var_0     float64
var_1     float64
var_2     float64
var_3     float64
var_4     float64
var_5     float64
var_6     float64
var_7     float64
var_8     float64
var_9     float64
var_10    float64
var_11    float64
var_12    float64
var_13    float64
var_14    float64
var_15    float64
var_16    float64
var_17    float64
dtype: object
Summary statistics for numerical columns in Train Data:

              target          var_0  ...         var_16         var_17
count  160000.000000  160000.000000  ...  160000.000000  160000.000000
mean        0.100175      10.677401  ...       9.337185      -5.700292
std         0.300234       3.039160  ...       2.558483       6.715098
min         0.000000       0.408400  ...       0.635100     -33.380200
25%         0.000000       8.452700  ...       7.455175     -10.485750
50%         0.000000      10.524750  ...       9.235850      -5.663200
75%         0.000000      12.759200  ...      11.064625      -0.810775
max         1.000000      20.315000  ...      17.950600      19.025900

[8 rows x 19 columns]

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using train_data as the DataFrame to check column information
column_info = get_column_info(train_data)
print("column_info")
print(column_info)

2025-08-30 17:13:33.408 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': [], 'Numeric': ['target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import StandardScale

# Copy the datasets to avoid modifying the original data
train_data_copy = train_data.copy()
eval_data_copy = eval_data.copy()

# Since there are no missing values and no categorical variables, we will only standardize the numerical features
# Initialize the StandardScale tool for numerical features
scaler = StandardScale(features=train_data_copy.columns.drop('target'))

# Fit the scaler on the training data and transform both the training and evaluation data
train_data_scaled = scaler.fit_transform(train_data_copy)
eval_data_scaled = scaler.transform(eval_data_copy)

# Display the first few rows of the scaled datasets
print("Scaled Train Data:")
display(train_data_scaled.head())
print("Scaled Eval Data:")
display(eval_data_scaled.head())

Scaled Train Data:

   target     var_0     var_1     var_2  ...    var_14    var_15    var_16    var_17
0       0  0.646003  1.127083  1.714367  ...  1.589015  1.217056 -1.751116  0.342869
1       0 -1.693697 -0.261292 -0.242032  ... -2.074646 -1.494532 -1.223731  1.833321
2       0 -0.425317  0.742922 -0.480017  ...  1.310002 -0.803466 -2.160930 -0.764460
3       0  0.276557 -1.021842  0.645635  ... -0.487786  0.708041 -0.298102  0.734912
4       0  0.649787 -1.085959  0.519556  ...  0.370346 -0.328435  0.828507  0.916906

[5 rows x 19 columns]

Scaled Eval Data:

   target     var_0     var_1     var_2  ...    var_14    var_15    var_16    var_17
0       1 -0.662291 -0.103380  0.593756  ... -0.595876 -0.629426  1.037421 -1.862914
1       1  2.502607  0.379510 -0.106631  ...  0.318415 -0.887938  0.592390  0.443047
2       0  1.057598  0.303822 -0.971334  ... -1.733733  0.980389 -0.100367 -1.260925
3       0 -0.798941  0.385874 -0.029893  ...  0.632494  0.027899 -2.341741  1.216366
4       0 -0.353652  1.078952 -1.834748  ...  0.106374 -1.514679  0.430848 -0.952976

[5 rows x 19 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the latest DataFrame from the finished tasks
column_info_train = get_column_info(train_data_scaled)
print("Column Info for Scaled Train Data:")
print(column_info_train)

column_info_eval = get_column_info(eval_data_scaled)
print("Column Info for Scaled Eval Data:")
print(column_info_eval)

Column Info for Scaled Train Data:
{'Category': [], 'Numeric': ['target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17'], 'Datetime': [], 'Others': []}
Column Info for Scaled Eval Data:
{'Category': [], 'Numeric': ['target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

# Split the training data into features and target
X_train = train_data_scaled.drop(columns=['target'])
y_train = train_data_scaled['target']

# Split the evaluation data into features and target
X_eval = eval_data_scaled.drop(columns=['target'])
y_eval = eval_data_scaled['target']

# Initialize the XGBoost classifier
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, scoring='roc_auc', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict probabilities on the evaluation set
y_pred_proba = best_model.predict_proba(X_eval)[:, 1]

# Calculate AUC score
auc_score = roc_auc_score(y_eval, y_pred_proba)
print(f"AUC Score on Evaluation Data: {auc_score:.4f}")

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py:158: UserWarning: [17:16:23] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

AUC Score on Evaluation Data: 0.6702