In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training dataset:")
display(train_df.head())
print("Testing dataset:")
display(test_df.head())

# Check the information of the datasets
print("Training dataset info:")
train_df.info()
print("Testing dataset info:")
test_df.info()

# Check for missing values
print("Missing values in training dataset:")
print(train_df.isnull().sum())
print("Missing values in testing dataset:")
print(test_df.isnull().sum())

# Summary statistics
print("Summary statistics for training dataset:")
display(train_df.describe(include='all'))

# Distribution of the target variable
sns.countplot(data=train_df, x='obesity_risk')
plt.title('Distribution of Obesity Risk in Training Dataset')
plt.show()

# Correlation matrix for numerical features
numeric_features = train_df.select_dtypes(include=[np.number]).columns
corr_matrix = train_df[numeric_features].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix for Numerical Features')
plt.show()

Training dataset:

      id  Gender  ...                 MTRANS           NObeyesdad
0   9958    Male  ...             Automobile       Obesity_Type_I
1   7841    Male  ...  Public_Transportation  Insufficient_Weight
2   9293    Male  ...  Public_Transportation      Obesity_Type_II
3  15209  Female  ...             Automobile       Obesity_Type_I
4  16515    Male  ...  Public_Transportation  Overweight_Level_II

[5 rows x 18 columns]

Testing dataset:

      id  Gender  ...                 MTRANS           NObeyesdad
0  10317  Female  ...  Public_Transportation     Obesity_Type_III
1   4074    Male  ...  Public_Transportation   Overweight_Level_I
2   9060  Female  ...  Public_Transportation       Obesity_Type_I
3  11286    Male  ...  Public_Transportation      Obesity_Type_II
4   8254    Male  ...  Public_Transportation  Insufficient_Weight

[5 rows x 18 columns]

Training dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16606 entries, 0 to 16605
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              16606 non-null  int64
 1   Gender                          16606 non-null  object
 2   Age                             16606 non-null  float64
 3   Height                          16606 non-null  float64
 4   Weight                          16606 non-null  float64
 5   family_history_with_overweight  16606 non-null  object
 6   FAVC                            16606 non-null  object
 7   FCVC                            16606 non-null  float64
 8   NCP                             16606 non-null  float64
 9   CAEC                            16606 non-null  object
 10  SMOKE                           16606 non-null  object
 11  CH2O                            16606 non-null  float64
 12  SCC                             16606 non-null  object
 13  FAF                             16606 non-null  float64
 14  TUE                             16606 non-null  float64
 15  CALC                            16606 non-null  object
 16  MTRANS                          16606 non-null  object
 17  NObeyesdad                      16606 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 2.3+ MB
Testing dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4152 entries, 0 to 4151
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4152 non-null   int64
 1   Gender                          4152 non-null   object
 2   Age                             4152 non-null   float64
 3   Height                          4152 non-null   float64
 4   Weight                          4152 non-null   float64
 5   family_history_with_overweight  4152 non-null   object
 6   FAVC                            4152 non-null   object
 7   FCVC                            4152 non-null   float64
 8   NCP                             4152 non-null   float64
 9   CAEC                            4152 non-null   object
 10  SMOKE                           4152 non-null   object
 11  CH2O                            4152 non-null   float64
 12  SCC                             4152 non-null   object
 13  FAF                             4152 non-null   float64
 14  TUE                             4152 non-null   float64
 15  CALC                            4152 non-null   object
 16  MTRANS                          4152 non-null   object
 17  NObeyesdad                      4152 non-null   object
dtypes: float64(8), int64(1), object(9)
memory usage: 584.0+ KB
Missing values in training dataset:
id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
Missing values in testing dataset:
id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
Summary statistics for training dataset:

                  id  Gender  ...                 MTRANS        NObeyesdad
count   16606.000000   16606  ...                  16606             16606
unique           NaN       2  ...                      5                 7
top              NaN  Female  ...  Public_Transportation  Obesity_Type_III
freq             NaN    8334  ...                  13328              3242
mean    10363.210888     NaN  ...                    NaN               NaN
std      5999.344301     NaN  ...                    NaN               NaN
min         0.000000     NaN  ...                    NaN               NaN
25%      5171.250000     NaN  ...                    NaN               NaN
50%     10377.500000     NaN  ...                    NaN               NaN
75%     15542.500000     NaN  ...                    NaN               NaN
max     20757.000000     NaN  ...                    NaN               NaN

[11 rows x 18 columns]

ValueError: Could not interpret value `obesity_risk` for `x`. An entry with this name does not appear in `data`.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training dataset:")
display(train_df.head())
print("Testing dataset:")
display(test_df.head())

# Check the information of the datasets
print("Training dataset info:")
train_df.info()
print("Testing dataset info:")
test_df.info()

# Check for missing values
print("Missing values in training dataset:")
print(train_df.isnull().sum())
print("Missing values in testing dataset:")
print(test_df.isnull().sum())

# Summary statistics
print("Summary statistics for training dataset:")
display(train_df.describe(include='all'))

# Distribution of the target variable
sns.countplot(data=train_df, x='NObeyesdad')
plt.title('Distribution of Obesity Risk in Training Dataset')
plt.show()

# Correlation matrix for numerical features
numeric_features = train_df.select_dtypes(include=[np.number]).columns
corr_matrix = train_df[numeric_features].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix for Numerical Features')
plt.show()

Training dataset:

      id  Gender  ...                 MTRANS           NObeyesdad
0   9958    Male  ...             Automobile       Obesity_Type_I
1   7841    Male  ...  Public_Transportation  Insufficient_Weight
2   9293    Male  ...  Public_Transportation      Obesity_Type_II
3  15209  Female  ...             Automobile       Obesity_Type_I
4  16515    Male  ...  Public_Transportation  Overweight_Level_II

[5 rows x 18 columns]

Testing dataset:

      id  Gender  ...                 MTRANS           NObeyesdad
0  10317  Female  ...  Public_Transportation     Obesity_Type_III
1   4074    Male  ...  Public_Transportation   Overweight_Level_I
2   9060  Female  ...  Public_Transportation       Obesity_Type_I
3  11286    Male  ...  Public_Transportation      Obesity_Type_II
4   8254    Male  ...  Public_Transportation  Insufficient_Weight

[5 rows x 18 columns]

Training dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16606 entries, 0 to 16605
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              16606 non-null  int64
 1   Gender                          16606 non-null  object
 2   Age                             16606 non-null  float64
 3   Height                          16606 non-null  float64
 4   Weight                          16606 non-null  float64
 5   family_history_with_overweight  16606 non-null  object
 6   FAVC                            16606 non-null  object
 7   FCVC                            16606 non-null  float64
 8   NCP                             16606 non-null  float64
 9   CAEC                            16606 non-null  object
 10  SMOKE                           16606 non-null  object
 11  CH2O                            16606 non-null  float64
 12  SCC                             16606 non-null  object
 13  FAF                             16606 non-null  float64
 14  TUE                             16606 non-null  float64
 15  CALC                            16606 non-null  object
 16  MTRANS                          16606 non-null  object
 17  NObeyesdad                      16606 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 2.3+ MB
Testing dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4152 entries, 0 to 4151
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4152 non-null   int64
 1   Gender                          4152 non-null   object
 2   Age                             4152 non-null   float64
 3   Height                          4152 non-null   float64
 4   Weight                          4152 non-null   float64
 5   family_history_with_overweight  4152 non-null   object
 6   FAVC                            4152 non-null   object
 7   FCVC                            4152 non-null   float64
 8   NCP                             4152 non-null   float64
 9   CAEC                            4152 non-null   object
 10  SMOKE                           4152 non-null   object
 11  CH2O                            4152 non-null   float64
 12  SCC                             4152 non-null   object
 13  FAF                             4152 non-null   float64
 14  TUE                             4152 non-null   float64
 15  CALC                            4152 non-null   object
 16  MTRANS                          4152 non-null   object
 17  NObeyesdad                      4152 non-null   object
dtypes: float64(8), int64(1), object(9)
memory usage: 584.0+ KB
Missing values in training dataset:
id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
Missing values in testing dataset:
id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
Summary statistics for training dataset:

                  id  Gender  ...                 MTRANS        NObeyesdad
count   16606.000000   16606  ...                  16606             16606
unique           NaN       2  ...                      5                 7
top              NaN  Female  ...  Public_Transportation  Obesity_Type_III
freq             NaN    8334  ...                  13328              3242
mean    10363.210888     NaN  ...                    NaN               NaN
std      5999.344301     NaN  ...                    NaN               NaN
min         0.000000     NaN  ...                    NaN               NaN
25%      5171.250000     NaN  ...                    NaN               NaN
50%     10377.500000     NaN  ...                    NaN               NaN
75%     15542.500000     NaN  ...                    NaN               NaN
max     20757.000000     NaN  ...                    NaN               NaN

[11 rows x 18 columns]

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 12:14:50.419 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': ['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'CALC', 'MTRANS', 'NObeyesdad'], 'Numeric': ['id', 'Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.feature_engineering import CatCount, TargetMeanEncoder, PolynomialExpansion, VarianceBasedSelection, GeneralSelection

# Copy the dataframes to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# Remove ID columns
train_df_copy.drop(columns=['id'], inplace=True)
test_df_copy.drop(columns=['id'], inplace=True)

# Feature Engineering
# 1. Categorical Count Encoding
cat_count = CatCount(col='Gender')
train_df_copy = cat_count.fit_transform(train_df_copy)
test_df_copy = cat_count.transform(test_df_copy)

# 2. Target Mean Encoding
target_mean_encoder = TargetMeanEncoder(col='family_history_with_overweight', label='NObeyesdad')
train_df_copy = target_mean_encoder.fit_transform(train_df_copy)
test_df_copy = target_mean_encoder.transform(test_df_copy)

# 3. Polynomial Expansion
poly_expansion = PolynomialExpansion(cols=['Age', 'Height', 'Weight'], label_col='NObeyesdad', degree=2)
train_df_copy = poly_expansion.fit_transform(train_df_copy)
test_df_copy = poly_expansion.transform(test_df_copy)

# 4. Variance Based Selection
variance_selector = VarianceBasedSelection(label_col='NObeyesdad', threshold=0.01)
train_df_copy = variance_selector.fit_transform(train_df_copy)
test_df_copy = variance_selector.transform(test_df_copy)

# 5. General Selection
general_selector = GeneralSelection(label_col='NObeyesdad')
train_df_copy = general_selector.fit_transform(train_df_copy)
test_df_copy = general_selector.transform(test_df_copy)

# Display the first few rows of the transformed datasets
print("Transformed Training dataset:")
display(train_df_copy.head())
print("Transformed Testing dataset:")
display(test_df_copy.head())

TypeError: agg function failed [how->mean,dtype->object]