In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/horse_health_outcomes/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/horse_health_outcomes/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Summary statistics
print("Summary Statistics for Training Data:")
display(train_df.describe(include='all'))

# Distinguish column types
numeric_features = train_df.select_dtypes(include=[np.number]).columns
categorical_features = train_df.select_dtypes(include=[np.object]).columns

# Visualize the distribution of numeric features
for feature in numeric_features:
    plt.figure(figsize=(10, 6))
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
    plt.show()

# Visualize the distribution of categorical features
for feature in categorical_features:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=train_df, x=feature)
    plt.title(f'Distribution of {feature}')
    plt.xticks(rotation=45)
    plt.show()

# Check the correlation matrix for numeric features
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

Training Data:

  surgery  hospital_number  ...  capillary_refill_time     outcome
0     yes           527706  ...             less_3_sec        died
1     yes           528641  ...             less_3_sec       lived
2     yes           535043  ...             more_3_sec  euthanized
3     yes           535043  ...             less_3_sec  euthanized
4     yes           528890  ...             more_3_sec        died

[5 rows x 9 columns]

Testing Data:

  surgery  hospital_number  ...  capillary_refill_time     outcome
0      no           535381  ...             less_3_sec  euthanized
1     yes           535029  ...             less_3_sec  euthanized
2     yes           529461  ...             more_3_sec        died
3     yes           534157  ...             less_3_sec  euthanized
4     yes           529777  ...             less_3_sec       lived

[5 rows x 9 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                986 non-null    object
 1   hospital_number        986 non-null    int64
 2   rectal_temp            986 non-null    float64
 3   pulse                  986 non-null    float64
 4   respiratory_rate       986 non-null    float64
 5   peripheral_pulse       938 non-null    object
 6   mucous_membrane        971 non-null    object
 7   capillary_refill_time  982 non-null    object
 8   outcome                986 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 69.5+ KB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                247 non-null    object
 1   hospital_number        247 non-null    int64
 2   rectal_temp            247 non-null    float64
 3   pulse                  247 non-null    float64
 4   respiratory_rate       247 non-null    float64
 5   peripheral_pulse       235 non-null    object
 6   mucous_membrane        241 non-null    object
 7   capillary_refill_time  245 non-null    object
 8   outcome                247 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 17.5+ KB
Missing values in Training Data:
surgery                   0
hospital_number           0
rectal_temp               0
pulse                     0
respiratory_rate          0
peripheral_pulse         48
mucous_membrane          15
capillary_refill_time     4
outcome                   0
dtype: int64
Missing values in Testing Data:
surgery                   0
hospital_number           0
rectal_temp               0
pulse                     0
respiratory_rate          0
peripheral_pulse         12
mucous_membrane           6
capillary_refill_time     2
outcome                   0
dtype: int64
Summary Statistics for Training Data:

       surgery  hospital_number  ...  capillary_refill_time  outcome
count      986     9.860000e+02  ...                    982      986
unique       2              NaN  ...                      2        3
top        yes              NaN  ...             less_3_sec    lived
freq       705              NaN  ...                    677      452
mean       NaN     9.746363e+05  ...                    NaN      NaN
std        NaN     1.385090e+06  ...                    NaN      NaN
min        NaN     5.213990e+05  ...                    NaN      NaN
25%        NaN     5.288010e+05  ...                    NaN      NaN
50%        NaN     5.297960e+05  ...                    NaN      NaN
75%        NaN     5.341450e+05  ...                    NaN      NaN
max        NaN     5.301219e+06  ...                    NaN      NaN

[11 rows x 9 columns]

C:\Users\xuyutian\AppData\Local\Temp\ipykernel_16224\1765857557.py:37: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  categorical_features = train_df.select_dtypes(include=[np.object]).columns

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/horse_health_outcomes/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/horse_health_outcomes/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Summary statistics
print("Summary Statistics for Training Data:")
display(train_df.describe(include='all'))

# Distinguish column types
numeric_features = train_df.select_dtypes(include=[np.number]).columns
categorical_features = train_df.select_dtypes(include=[object]).columns

# Visualize the distribution of numeric features
for feature in numeric_features:
    plt.figure(figsize=(10, 6))
    sns.histplot(train_df[feature], kde=True)
    plt.title(f'Distribution of {feature}')
    plt.show()

# Visualize the distribution of categorical features
for feature in categorical_features:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=train_df, x=feature)
    plt.title(f'Distribution of {feature}')
    plt.xticks(rotation=45)
    plt.show()

# Check the correlation matrix for numeric features
plt.figure(figsize=(12, 8))
sns.heatmap(train_df[numeric_features].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numeric Features')
plt.show()

Training Data:

  surgery  hospital_number  ...  capillary_refill_time     outcome
0     yes           527706  ...             less_3_sec        died
1     yes           528641  ...             less_3_sec       lived
2     yes           535043  ...             more_3_sec  euthanized
3     yes           535043  ...             less_3_sec  euthanized
4     yes           528890  ...             more_3_sec        died

[5 rows x 9 columns]

Testing Data:

  surgery  hospital_number  ...  capillary_refill_time     outcome
0      no           535381  ...             less_3_sec  euthanized
1     yes           535029  ...             less_3_sec  euthanized
2     yes           529461  ...             more_3_sec        died
3     yes           534157  ...             less_3_sec  euthanized
4     yes           529777  ...             less_3_sec       lived

[5 rows x 9 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                986 non-null    object
 1   hospital_number        986 non-null    int64
 2   rectal_temp            986 non-null    float64
 3   pulse                  986 non-null    float64
 4   respiratory_rate       986 non-null    float64
 5   peripheral_pulse       938 non-null    object
 6   mucous_membrane        971 non-null    object
 7   capillary_refill_time  982 non-null    object
 8   outcome                986 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 69.5+ KB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                247 non-null    object
 1   hospital_number        247 non-null    int64
 2   rectal_temp            247 non-null    float64
 3   pulse                  247 non-null    float64
 4   respiratory_rate       247 non-null    float64
 5   peripheral_pulse       235 non-null    object
 6   mucous_membrane        241 non-null    object
 7   capillary_refill_time  245 non-null    object
 8   outcome                247 non-null    object
dtypes: float64(3), int64(1), object(5)
memory usage: 17.5+ KB
Missing values in Training Data:
surgery                   0
hospital_number           0
rectal_temp               0
pulse                     0
respiratory_rate          0
peripheral_pulse         48
mucous_membrane          15
capillary_refill_time     4
outcome                   0
dtype: int64
Missing values in Testing Data:
surgery                   0
hospital_number           0
rectal_temp               0
pulse                     0
respiratory_rate          0
peripheral_pulse         12
mucous_membrane           6
capillary_refill_time     2
outcome                   0
dtype: int64
Summary Statistics for Training Data:

       surgery  hospital_number  ...  capillary_refill_time  outcome
count      986     9.860000e+02  ...                    982      986
unique       2              NaN  ...                      2        3
top        yes              NaN  ...             less_3_sec    lived
freq       705              NaN  ...                    677      452
mean       NaN     9.746363e+05  ...                    NaN      NaN
std        NaN     1.385090e+06  ...                    NaN      NaN
min        NaN     5.213990e+05  ...                    NaN      NaN
25%        NaN     5.288010e+05  ...                    NaN      NaN
50%        NaN     5.297960e+05  ...                    NaN      NaN
75%        NaN     5.341450e+05  ...                    NaN      NaN
max        NaN     5.301219e+06  ...                    NaN      NaN

[11 rows x 9 columns]

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 12:32:35.350 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': ['surgery', 'peripheral_pulse', 'mucous_membrane', 'capillary_refill_time', 'outcome'], 'Numeric': ['hospital_number', 'rectal_temp', 'pulse', 'respiratory_rate'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import FillMissingValue, LabelEncode, StandardScale

# Copy the datasets to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# Handling missing values
fill_missing_value = FillMissingValue(features=['peripheral_pulse', 'mucous_membrane', 'capillary_refill_time'], strategy='most_frequent')
train_df_copy = fill_missing_value.fit_transform(train_df_copy)
test_df_copy = fill_missing_value.transform(test_df_copy)

# Encoding categorical variables
label_encode = LabelEncode(features=['surgery', 'peripheral_pulse', 'mucous_membrane', 'capillary_refill_time', 'outcome'])
train_df_copy = label_encode.fit_transform(train_df_copy)
test_df_copy = label_encode.transform(test_df_copy)

# Scaling numeric features
standard_scale = StandardScale(features=['hospital_number', 'rectal_temp', 'pulse', 'respiratory_rate'])
train_df_copy = standard_scale.fit_transform(train_df_copy)
test_df_copy = standard_scale.transform(test_df_copy)

# Display the first few rows of the preprocessed datasets
print("Preprocessed Training Data:")
display(train_df_copy.head())
print("Preprocessed Testing Data:")
display(test_df_copy.head())

Preprocessed Training Data:

   surgery  hospital_number  ...  capillary_refill_time  outcome
0        2        -0.322836  ...                      0        0
1        2        -0.322161  ...                      0        2
2        2        -0.317536  ...                      1        1
3        2        -0.317536  ...                      0        1
4        2        -0.321981  ...                      1        0

[5 rows x 9 columns]

Preprocessed Testing Data:

   surgery  hospital_number  ...  capillary_refill_time  outcome
0        0        -0.317292  ...                      0        1
1        2        -0.317546  ...                      0        1
2        2        -0.321568  ...                      1        0
3        2        -0.318176  ...                      0        1
4        2        -0.321340  ...                      0        2

[5 rows x 9 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the preprocessed training data DataFrame
column_info = get_column_info(train_df_copy)
print("column_info")
print(column_info)

column_info
{'Category': [], 'Numeric': ['surgery', 'hospital_number', 'rectal_temp', 'pulse', 'respiratory_rate', 'peripheral_pulse', 'mucous_membrane', 'capillary_refill_time', 'outcome'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import f1_score
from xgboost import XGBClassifier

# Split the preprocessed training data into features and target
X_train = train_df_copy.drop('outcome', axis=1)
y_train = train_df_copy['outcome']

# Split the preprocessed testing data into features and target
X_test = test_df_copy.drop('outcome', axis=1)
y_test = test_df_copy['outcome']

# Initialize the XGBoost classifier
xgb = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, scoring='f1_macro', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on the test set
y_pred = best_model.predict(X_test)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred, average='macro')

# Print the F1 score
print(f"Test Set F1 Score: {f1:.4f}")

# Save the predictions
test_df_copy['predicted_outcome'] = y_pred
test_df_copy.to_csv('predicted_horse_health_outcomes.csv', index=False)

Test Set F1 Score: 0.6100

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py:158: UserWarning: [12:33:39] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)