In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Summary statistics for numerical columns
print("Summary statistics for Training Data:")
display(train_df.describe())
print("Summary statistics for Testing Data:")
display(test_df.describe())

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.countplot(data=train_df, x='category')
plt.title('Distribution of Crime Categories in Training Data')
plt.xticks(rotation=90)
plt.show()

# Correlation matrix for numerical columns
plt.figure(figsize=(12, 8))
corr_matrix = train_df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix for Numerical Columns in Training Data')
plt.show()

Training Data:

        Category  DayOfWeek PdDistrict           X          Y
0  LARCENY/THEFT  Wednesday   SOUTHERN -122.388380  37.783310
1   NON-CRIMINAL   Saturday   SOUTHERN -122.403405  37.775421
2  LARCENY/THEFT  Wednesday   NORTHERN -122.419581  37.789214
3  VEHICLE THEFT     Friday    BAYVIEW -122.389744  37.757909
4        ASSAULT     Friday    TARAVAL -122.478377  37.742877

Testing Data:

         Category  DayOfWeek  PdDistrict           X          Y
0   VEHICLE THEFT     Sunday    SOUTHERN -122.409893  37.780113
1        BURGLARY     Monday    NORTHERN -122.424442  37.788227
2  OTHER OFFENSES  Wednesday     BAYVIEW -122.395635  37.753565
3        BURGLARY    Tuesday        PARK -122.444802  37.754171
4    NON-CRIMINAL   Saturday  TENDERLOIN -122.412971  37.785788

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70244 entries, 0 to 70243
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Category    70244 non-null  object
 1   DayOfWeek   70244 non-null  object
 2   PdDistrict  70244 non-null  object
 3   X           70244 non-null  float64
 4   Y           70244 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.7+ MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17560 entries, 0 to 17559
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Category    17560 non-null  object
 1   DayOfWeek   17560 non-null  object
 2   PdDistrict  17560 non-null  object
 3   X           17560 non-null  float64
 4   Y           17560 non-null  float64
dtypes: float64(2), object(3)
memory usage: 686.1+ KB
Missing values in Training Data:
Category      0
DayOfWeek     0
PdDistrict    0
X             0
Y             0
dtype: int64
Missing values in Testing Data:
Category      0
DayOfWeek     0
PdDistrict    0
X             0
Y             0
dtype: int64
Summary statistics for Training Data:

                  X             Y
count  70244.000000  70244.000000
mean    -122.422808     37.767867
std        0.026338      0.198551
min     -122.513642     37.707944
25%     -122.432915     37.752590
50%     -122.416452     37.775421
75%     -122.406992     37.784400
max     -120.500000     90.000000

Summary statistics for Testing Data:

                  X             Y
count  17560.000000  17560.000000
mean    -122.423049     37.769936
std        0.029409      0.394910
min     -122.513642     37.707968
25%     -122.433359     37.752504
50%     -122.416583     37.775421
75%     -122.406959     37.784353
max     -120.500000     90.000000

ValueError: Could not interpret value `category` for `x`. An entry with this name does not appear in `data`.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the information of the datasets
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Check for missing values
print("Missing values in Training Data:")
print(train_df.isnull().sum())
print("Missing values in Testing Data:")
print(test_df.isnull().sum())

# Summary statistics for numerical columns
print("Summary statistics for Training Data:")
display(train_df.describe())
print("Summary statistics for Testing Data:")
display(test_df.describe())

# Distribution of the target variable
plt.figure(figsize=(10, 6))
sns.countplot(data=train_df, x='Category')
plt.title('Distribution of Crime Categories in Training Data')
plt.xticks(rotation=90)
plt.show()

# Correlation matrix for numerical columns
plt.figure(figsize=(12, 8))
corr_matrix = train_df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix for Numerical Columns in Training Data')
plt.show()

Training Data:

        Category  DayOfWeek PdDistrict           X          Y
0  LARCENY/THEFT  Wednesday   SOUTHERN -122.388380  37.783310
1   NON-CRIMINAL   Saturday   SOUTHERN -122.403405  37.775421
2  LARCENY/THEFT  Wednesday   NORTHERN -122.419581  37.789214
3  VEHICLE THEFT     Friday    BAYVIEW -122.389744  37.757909
4        ASSAULT     Friday    TARAVAL -122.478377  37.742877

Testing Data:

         Category  DayOfWeek  PdDistrict           X          Y
0   VEHICLE THEFT     Sunday    SOUTHERN -122.409893  37.780113
1        BURGLARY     Monday    NORTHERN -122.424442  37.788227
2  OTHER OFFENSES  Wednesday     BAYVIEW -122.395635  37.753565
3        BURGLARY    Tuesday        PARK -122.444802  37.754171
4    NON-CRIMINAL   Saturday  TENDERLOIN -122.412971  37.785788

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70244 entries, 0 to 70243
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Category    70244 non-null  object
 1   DayOfWeek   70244 non-null  object
 2   PdDistrict  70244 non-null  object
 3   X           70244 non-null  float64
 4   Y           70244 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.7+ MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17560 entries, 0 to 17559
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Category    17560 non-null  object
 1   DayOfWeek   17560 non-null  object
 2   PdDistrict  17560 non-null  object
 3   X           17560 non-null  float64
 4   Y           17560 non-null  float64
dtypes: float64(2), object(3)
memory usage: 686.1+ KB
Missing values in Training Data:
Category      0
DayOfWeek     0
PdDistrict    0
X             0
Y             0
dtype: int64
Missing values in Testing Data:
Category      0
DayOfWeek     0
PdDistrict    0
X             0
Y             0
dtype: int64
Summary statistics for Training Data:

                  X             Y
count  70244.000000  70244.000000
mean    -122.422808     37.767867
std        0.026338      0.198551
min     -122.513642     37.707944
25%     -122.432915     37.752590
50%     -122.416452     37.775421
75%     -122.406992     37.784400
max     -120.500000     90.000000

Summary statistics for Testing Data:

                  X             Y
count  17560.000000  17560.000000
mean    -122.423049     37.769936
std        0.029409      0.394910
min     -122.513642     37.707968
25%     -122.433359     37.752504
50%     -122.416583     37.775421
75%     -122.406959     37.784353
max     -120.500000     90.000000

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info_train = get_column_info(train_df)
print("Column Information for Training Data:")
print(column_info_train)

# Using the test_df DataFrame from the finished tasks
column_info_test = get_column_info(test_df)
print("Column Information for Testing Data:")
print(column_info_test)

2025-08-31 13:40:07.514 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

Column Information for Training Data:
{'Category': ['Category', 'DayOfWeek', 'PdDistrict'], 'Numeric': ['X', 'Y'], 'Datetime': [], 'Others': []}
Column Information for Testing Data:
{'Category': ['Category', 'DayOfWeek', 'PdDistrict'], 'Numeric': ['X', 'Y'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import LabelEncode, StandardScale

# Copy the dataframes to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# Encode categorical variables
categorical_features = ['DayOfWeek', 'PdDistrict']
label_encoder = LabelEncode(features=categorical_features)
train_df_encoded = label_encoder.fit_transform(train_df_copy)
test_df_encoded = label_encoder.transform(test_df_copy)

# Scale numerical features
numeric_features = ['X', 'Y']
scaler = StandardScale(features=numeric_features)
train_df_scaled = scaler.fit_transform(train_df_encoded)
test_df_scaled = scaler.transform(test_df_encoded)

# Display the first few rows of the preprocessed data
print("Preprocessed Training Data:")
display(train_df_scaled.head())
print("Preprocessed Testing Data:")
display(test_df_scaled.head())

Preprocessed Training Data:

        Category  DayOfWeek  PdDistrict         X         Y
0  LARCENY/THEFT          6           7  1.307195  0.077780
1   NON-CRIMINAL          2           7  0.736721  0.038043
2  LARCENY/THEFT          6           4  0.122545  0.107514
3  VEHICLE THEFT          0           0  1.255416 -0.050156
4        ASSAULT          0           8 -2.109862 -0.125866

Preprocessed Testing Data:

         Category  DayOfWeek  PdDistrict         X         Y
0   VEHICLE THEFT          3           7  0.490380  0.061678
1        BURGLARY          1           4 -0.062032  0.102543
2  OTHER OFFENSES          6           0  1.031712 -0.072036
3        BURGLARY          5           5 -0.835081 -0.068983
4    NON-CRIMINAL          2           9  0.373523  0.090260

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the preprocessed training data DataFrame
column_info = get_column_info(train_df_scaled)
print("column_info")
print(column_info)

column_info
{'Category': ['Category'], 'Numeric': ['DayOfWeek', 'PdDistrict', 'X', 'Y'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# Prepare the data
X_train = train_df_scaled.drop('Category', axis=1)
y_train = train_df_scaled['Category']
X_test = test_df_scaled.drop('Category', axis=1)
y_test = test_df_scaled['Category']

# Encode the target variable
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Train the model
model = XGBClassifier(
    n_estimators=1000,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    eval_metric='mlogloss'
)
model.fit(X_train, y_train_encoded)

# Predict on the test set
y_pred_proba = model.predict_proba(X_test)

# Calculate log loss
logloss = log_loss(y_test_encoded, y_pred_proba)
print(f"Log Loss on the test set: {logloss:.4f}")

# Save the predictions
predictions = pd.DataFrame(y_pred_proba, columns=label_encoder.classes_)
predictions.to_csv('predictions.csv', index=False)

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\xgboost\core.py:158: UserWarning: [13:40:48] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Log Loss on the test set: 2.5673