In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crab_age/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crab_age/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the data types and basic statistics
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Summary statistics for numerical columns
print("Training Data Descriptive Statistics:")
display(train_df.describe())
print("Testing Data Descriptive Statistics:")
display(test_df.describe())

# Check for missing values
print("Missing values in Training Data:")
display(train_df.isnull().sum())
print("Missing values in Testing Data:")
display(test_df.isnull().sum())

# Visualize the distribution of the target variable (age)
plt.figure(figsize=(10, 6))
sns.histplot(train_df['age'], bins=30, kde=True)
plt.title('Distribution of Age in Training Data')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Visualize the correlation matrix for numerical features
plt.figure(figsize=(12, 8))
corr_matrix = train_df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numerical Features in Training Data')
plt.show()

Training Data:

      id Sex  Length  ...  Viscera_Weight  Shell_Weight  Age
0  20612   M  1.6125  ...        6.265239      7.059025    9
1   2935   F  1.5250  ...        7.002326      8.930093   10
2  73847   M  1.5000  ...        6.166016      8.079607   12
3  46445   M  1.1250  ...        2.891649      3.685435   10
4  66755   I  0.8625  ...        0.737087      1.275727    6

[5 rows x 10 columns]

Testing Data:

      id Sex  Length  ...  Viscera_Weight  Shell_Weight  Age
0  27233   I  1.6125  ...        6.435337     11.056305   18
1  55493   I  0.6625  ...        0.581165      0.793786    6
2  49980   M  1.3500  ...        5.684075      6.236890    8
3  28319   I  1.1125  ...        1.615922      3.401940    8
4  20212   I  1.0375  ...        1.686795      2.409708    8

[5 rows x 10 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59240 entries, 0 to 59239
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              59240 non-null  int64
 1   Sex             59240 non-null  object
 2   Length          59240 non-null  float64
 3   Diameter        59240 non-null  float64
 4   Height          59240 non-null  float64
 5   Weight          59240 non-null  float64
 6   Shucked_Weight  59240 non-null  float64
 7   Viscera_Weight  59240 non-null  float64
 8   Shell_Weight    59240 non-null  float64
 9   Age             59240 non-null  int64
dtypes: float64(7), int64(2), object(1)
memory usage: 4.5+ MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14811 entries, 0 to 14810
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              14811 non-null  int64
 1   Sex             14811 non-null  object
 2   Length          14811 non-null  float64
 3   Diameter        14811 non-null  float64
 4   Height          14811 non-null  float64
 5   Weight          14811 non-null  float64
 6   Shucked_Weight  14811 non-null  float64
 7   Viscera_Weight  14811 non-null  float64
 8   Shell_Weight    14811 non-null  float64
 9   Age             14811 non-null  int64
dtypes: float64(7), int64(2), object(1)
memory usage: 1.1+ MB
Training Data Descriptive Statistics:

                 id        Length  ...  Shell_Weight           Age
count  59240.000000  59240.000000  ...  59240.000000  59240.000000
mean   36996.215851      1.318072  ...      6.727251      9.970172
std    21390.146701      0.287125  ...      3.578669      3.170861
min        0.000000      0.187500  ...      0.042524      1.000000
25%    18453.750000      1.150000  ...      3.968930      8.000000
50%    37002.500000      1.375000  ...      6.917278     10.000000
75%    55575.500000      1.537500  ...      9.071840     11.000000
max    74050.000000      2.012815  ...     28.491248     29.000000

[8 rows x 9 columns]

Testing Data Descriptive Statistics:

                 id        Length  ...  Shell_Weight           Age
count  14811.000000  14811.000000  ...  14811.000000  14811.000000
mean   37140.128823      1.315013  ...      6.710346      9.958342
std    21323.799514      0.290267  ...      3.607181      3.192531
min        4.000000      0.325000  ...      0.099223      1.000000
25%    18770.500000      1.150000  ...      3.827183      8.000000
50%    37110.000000      1.375000  ...      6.945627     10.000000
75%    55401.500000      1.537500  ...      9.100190     11.000000
max    74041.000000      1.950000  ...     25.429502     29.000000

[8 rows x 9 columns]

Missing values in Training Data:

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Age               0
dtype: int64

Missing values in Testing Data:

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Age               0
dtype: int64

KeyError: 'age'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crab_age/train.csv'
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crab_age/test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and testing datasets
print("Training Data:")
display(train_df.head())
print("Testing Data:")
display(test_df.head())

# Check the data types and basic statistics
print("Training Data Info:")
train_df.info()
print("Testing Data Info:")
test_df.info()

# Summary statistics for numerical columns
print("Training Data Descriptive Statistics:")
display(train_df.describe())
print("Testing Data Descriptive Statistics:")
display(test_df.describe())

# Check for missing values
print("Missing values in Training Data:")
display(train_df.isnull().sum())
print("Missing values in Testing Data:")
display(test_df.isnull().sum())

# Ensure column names are consistent
train_df.columns = train_df.columns.str.lower()
test_df.columns = test_df.columns.str.lower()

# Visualize the distribution of the target variable (age)
plt.figure(figsize=(10, 6))
sns.histplot(train_df['age'], bins=30, kde=True)
plt.title('Distribution of Age in Training Data')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Visualize the correlation matrix for numerical features
plt.figure(figsize=(12, 8))
corr_matrix = train_df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numerical Features in Training Data')
plt.show()

Training Data:

      id Sex  Length  ...  Viscera_Weight  Shell_Weight  Age
0  20612   M  1.6125  ...        6.265239      7.059025    9
1   2935   F  1.5250  ...        7.002326      8.930093   10
2  73847   M  1.5000  ...        6.166016      8.079607   12
3  46445   M  1.1250  ...        2.891649      3.685435   10
4  66755   I  0.8625  ...        0.737087      1.275727    6

[5 rows x 10 columns]

Testing Data:

      id Sex  Length  ...  Viscera_Weight  Shell_Weight  Age
0  27233   I  1.6125  ...        6.435337     11.056305   18
1  55493   I  0.6625  ...        0.581165      0.793786    6
2  49980   M  1.3500  ...        5.684075      6.236890    8
3  28319   I  1.1125  ...        1.615922      3.401940    8
4  20212   I  1.0375  ...        1.686795      2.409708    8

[5 rows x 10 columns]

Training Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59240 entries, 0 to 59239
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              59240 non-null  int64
 1   Sex             59240 non-null  object
 2   Length          59240 non-null  float64
 3   Diameter        59240 non-null  float64
 4   Height          59240 non-null  float64
 5   Weight          59240 non-null  float64
 6   Shucked_Weight  59240 non-null  float64
 7   Viscera_Weight  59240 non-null  float64
 8   Shell_Weight    59240 non-null  float64
 9   Age             59240 non-null  int64
dtypes: float64(7), int64(2), object(1)
memory usage: 4.5+ MB
Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14811 entries, 0 to 14810
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              14811 non-null  int64
 1   Sex             14811 non-null  object
 2   Length          14811 non-null  float64
 3   Diameter        14811 non-null  float64
 4   Height          14811 non-null  float64
 5   Weight          14811 non-null  float64
 6   Shucked_Weight  14811 non-null  float64
 7   Viscera_Weight  14811 non-null  float64
 8   Shell_Weight    14811 non-null  float64
 9   Age             14811 non-null  int64
dtypes: float64(7), int64(2), object(1)
memory usage: 1.1+ MB
Training Data Descriptive Statistics:

                 id        Length  ...  Shell_Weight           Age
count  59240.000000  59240.000000  ...  59240.000000  59240.000000
mean   36996.215851      1.318072  ...      6.727251      9.970172
std    21390.146701      0.287125  ...      3.578669      3.170861
min        0.000000      0.187500  ...      0.042524      1.000000
25%    18453.750000      1.150000  ...      3.968930      8.000000
50%    37002.500000      1.375000  ...      6.917278     10.000000
75%    55575.500000      1.537500  ...      9.071840     11.000000
max    74050.000000      2.012815  ...     28.491248     29.000000

[8 rows x 9 columns]

Testing Data Descriptive Statistics:

                 id        Length  ...  Shell_Weight           Age
count  14811.000000  14811.000000  ...  14811.000000  14811.000000
mean   37140.128823      1.315013  ...      6.710346      9.958342
std    21323.799514      0.290267  ...      3.607181      3.192531
min        4.000000      0.325000  ...      0.099223      1.000000
25%    18770.500000      1.150000  ...      3.827183      8.000000
50%    37110.000000      1.375000  ...      6.945627     10.000000
75%    55401.500000      1.537500  ...      9.100190     11.000000
max    74041.000000      1.950000  ...     25.429502     29.000000

[8 rows x 9 columns]

Missing values in Training Data:

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Age               0
dtype: int64

Missing values in Testing Data:

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Age               0
dtype: int64

In [3]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the train_df DataFrame from the finished tasks
column_info = get_column_info(train_df)
print("column_info")
print(column_info)

2025-08-31 14:05:10.433 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter

column_info
{'Category': ['sex'], 'Numeric': ['id', 'length', 'diameter', 'height', 'weight', 'shucked_weight', 'viscera_weight', 'shell_weight', 'age'], 'Datetime': [], 'Others': []}

In [4]:
from metagpt.tools.libs.data_preprocess import OneHotEncode

# Copy the dataframes to avoid modifying the original data
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

# One-hot encode the categorical feature 'sex'
one_hot_encoder = OneHotEncode(features=['sex'])
train_df_encoded = one_hot_encoder.fit_transform(train_df_copy)
test_df_encoded = one_hot_encoder.transform(test_df_copy)

# Split the data into features and target variables
X_train = train_df_encoded.drop(columns=['age'])
y_train = train_df_encoded['age']
X_test = test_df_encoded.drop(columns=['age'])
y_test = test_df_encoded['age']

# Display the first few rows of the processed data
print("Processed Training Data:")
display(X_train.head())
print("Processed Testing Data:")
display(X_test.head())

Processed Training Data:

D:\LLM-Driven_AI-Studio\MLAgent\experiments\DataInterpreter\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

      id  length  diameter  height  ...  shell_weight  sex_F  sex_I  sex_M
0  20612  1.6125    1.1500  0.4000  ...      7.059025    0.0    0.0    1.0
1   2935  1.5250    1.1750  0.4125  ...      8.930093    1.0    0.0    0.0
2  73847  1.5000    1.1625  0.3875  ...      8.079607    0.0    0.0    1.0
3  46445  1.1250    0.8875  0.2375  ...      3.685435    0.0    0.0    1.0
4  66755  0.8625    0.6375  0.1875  ...      1.275727    0.0    1.0    0.0

[5 rows x 11 columns]

Processed Testing Data:

      id  length  diameter  height  ...  shell_weight  sex_F  sex_I  sex_M
0  27233  1.6125     1.350  0.4375  ...     11.056305    0.0    1.0    0.0
1  55493  0.6625     0.500  0.1625  ...      0.793786    0.0    1.0    0.0
2  49980  1.3500     1.050  0.3000  ...      6.236890    0.0    0.0    1.0
3  28319  1.1125     0.800  0.2750  ...      3.401940    0.0    1.0    0.0
4  20212  1.0375     0.825  0.2500  ...      2.409708    0.0    1.0    0.0

[5 rows x 11 columns]

In [5]:
from metagpt.tools.libs.data_preprocess import get_column_info

# Using the latest processed dataframes
column_info_train = get_column_info(X_train)
column_info_test = get_column_info(X_test)

print("Column Information for Processed Training Data:")
print(column_info_train)
print("\nColumn Information for Processed Testing Data:")
print(column_info_test)

Column Information for Processed Training Data:
{'Category': [], 'Numeric': ['id', 'length', 'diameter', 'height', 'weight', 'shucked_weight', 'viscera_weight', 'shell_weight', 'sex_F', 'sex_I', 'sex_M'], 'Datetime': [], 'Others': []}

Column Information for Processed Testing Data:
{'Category': [], 'Numeric': ['id', 'length', 'diameter', 'height', 'weight', 'shucked_weight', 'viscera_weight', 'shell_weight', 'sex_F', 'sex_I', 'sex_M'], 'Datetime': [], 'Others': []}

In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Initialize the Random Forest Regressor with some hyperparameters
rf_regressor = RandomForestRegressor(n_estimators=100, max_depth=20, random_state=42)

# Train the model
rf_regressor.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_regressor.predict(X_test)

# Calculate the Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error on the test set: {mae:.2f}")

# Save the predictions
predictions = pd.DataFrame({'id': test_df['id'], 'predicted_age': y_pred})
predictions.to_csv('crab_age_predictions.csv', index=False)
print("Predictions saved to 'crab_age_predictions.csv'")

Mean Absolute Error on the test set: 1.45
Predictions saved to 'crab_age_predictions.csv'